#!/usr/bin/env python3
"""Regression checks for the Premium-only Ticket AI rollout."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
AI = (ROOT / "bot/utils/ticket_ai.py").read_text(encoding="utf-8")
SCAN = (ROOT / "bot/utils/ticket_ai_scan.py").read_text(encoding="utf-8")
TICKET = (ROOT / "bot/cogs/commands/ticket.py").read_text(encoding="utf-8")
API = (ROOT / "bot/api/routes/tickets.py").read_text(encoding="utf-8")
ADMIN_API = (ROOT / "bot/api/routes/admin.py").read_text(encoding="utf-8")
PAGE = (ROOT / "dashboard/app/dashboard/guild/[guildId]/tickets/page.tsx").read_text(encoding="utf-8")
PANEL = (ROOT / "dashboard/components/dashboard/ticket-ai-panel.tsx").read_text(encoding="utf-8")
ADMIN_PANEL = (ROOT / "dashboard/components/dashboard/ticket-ai-admin.tsx").read_text(encoding="utf-8")
PREMIUM_ADMIN = (ROOT / "dashboard/components/dashboard/premium-admin.tsx").read_text(encoding="utf-8")
PREMIUM_GUILDS = (ROOT / "dashboard/components/dashboard/premium-guilds.tsx").read_text(encoding="utf-8")
ADMIN_CONTENT = (ROOT / "dashboard/components/dashboard/admin-content.tsx").read_text(encoding="utf-8")
BFF = (ROOT / "dashboard/app/api/bot/[...path]/route.ts").read_text(encoding="utf-8")

failures: list[str] = []
def check(label: str, condition: bool) -> None:
    print(f"  {'ok  ' if condition else 'FAIL'} {label}")
    if not condition: failures.append(label)

pilot = "1530378233579704370"
check("initial pilot remains enabled on first rollout", pilot in AI and "first_setup" in AI)
check("access is persisted and admin-managed", "ticket_ai_access" in AI and "/ticket-ai-access" in ADMIN_API and "set_ticket_ai_access" in ADMIN_API)
check("revoking the initial pilot remains revoked", "INSERT OR IGNORE INTO ticket_ai_access" not in AI and "if first_setup" in AI)
check("non-allowlisted guild APIs disclose nothing", "is_allowlisted(guild_id)" in API and 'status_code=404' in API and 'detail="Not found."' in API)
check("server Premium remains enforced", "pilot_available(guild_id)" in API and "ticket_ai.pilot_available(message.guild.id)" in TICKET)
check("listener no longer hardcodes one server", "message.guild.id != ticket_ai.PILOT_GUILD_ID" not in TICKET)
check("admin has a complete Ticket AI tab", 'id: "ticketai"' in ADMIN_CONTENT and '<TicketAiAdmin />' in ADMIN_CONTENT and "Serverfreigaben" in ADMIN_PANEL)
check("admin endpoint has premium.manage permission", '"ticket-ai-access": { GET: "premium.manage", WRITE: "premium.manage" }' in BFF)
check("Premium admin manages individual servers", 'id: "server"' in PREMIUM_ADMIN and "<PremiumGuilds />" in PREMIUM_ADMIN and "/premium-guilds" in ADMIN_API and "setGuildPremium" in PREMIUM_GUILDS)
check("server Premium mutations are permission gated", '"premium-guilds": { GET: "premium.manage" }' in BFF and 'premium: { WRITE: "premium.manage" }' in BFF)
check("AI switch persists immediately", "const setEnabled = async" in PANEL and "onClick={() => setEnabled(!data.enabled)}" in PANEL and "disabled={busy}" in PANEL)
check("missing prerequisites explain instead of silently disabling", "Lade zuerst eine .txt-Wissensdatei hoch" in PANEL and "GROQ_TICKET_AI_KEY fehlt oder enthält keinen gültigen Groq-Key" in PANEL)
check("dashboard loader always settles", "finally" in PANEL and "setLoading(false)" in PANEL and "loadError" in PANEL and "Erneut versuchen" in PANEL and "12000" in PANEL)
check("other servers see no feature flash", "getTicketAiAvailability" in PANEL and "if (!visibility.available)" in PANEL and "if (unavailable || (loading && !data && !loadError)) return null" in PANEL and "<TicketAiPanel" in PAGE)
check("Railway secret uses a valid environment name", 'API_KEY_ENV = "GROQ_TICKET_AI_KEY"' in AI)
check("Groq uses production models with fallbacks", 'DEFAULT_MODEL = "openai/gpt-oss-120b"' in AI and '"llama-3.1-8b-instant"' in AI and "model_candidates()" in AI and "response.status_code == 404" in AI)
check("Groq key never appears in request URLs or errors", '"Authorization": f"Bearer {key}"' in AI and 'params={"key": key}' not in AI and "GROQ_CHAT_URL" in AI)
check("non-Groq keys are rejected before a scan", 'key.startswith("gsk_")' in AI and "keinen gültigen Groq-Key" in API)
check("HTTP 400 retries without optional model parameters", "response.status_code == 400" in AI and '"model": model, "messages": messages, "stream": False' in AI and "_groq_error(response)" in AI)
check("Groq rate limits wait and retry automatically", "response.status_code != 429" in AI and "_rate_limit_delay(response, attempt)" in AI and "await asyncio.sleep" in AI)
check("scan requests stay below the Groq on-demand TPM ceiling", "CHUNK_SIZE = 4_000" in SCAN and "max_tokens=1200" in SCAN and "for offset in range" in SCAN)
check("Ticket AI contains only the Groq provider integration", all(word not in (AI + SCAN + API + PANEL + ADMIN_PANEL).lower() for word in ("google", "gemini", "generativelanguage", "api.x.ai", "xai_ticket", "grok-4")))
check("only txt up to 100 KB is accepted", "endswith(\".txt\")" in API and "MAX_KNOWLEDGE_BYTES" in API and "100 KB" in PANEL)
check("knowledge stays guild scoped", "ticket_ai_knowledge" in AI and "WHERE guild_id = ?" in API)
check("only the ticket creator triggers AI", 'int(ticket["creator_id"]) != message.author.id' in TICKET)
check("claimed and closed tickets never answer", TICKET.count('current["is_claimed"]') >= 1 and 'current["closed_at"]' in TICKET)
check("claim race is rechecked during Groq requests", "Claim can happen while the Groq request is running" in TICKET)
check("categories independently enable AI", "ticket_ai_categories" in AI and 'config["category_enabled"]' in TICKET)
check("Groq receives excerpts instead of complete knowledge", "matching_context" in AI and "excerpts" in TICKET and "source[:5000]" in AI)
check("prompt blocks unsupported answers and injection", "AUSSCHLIESSLICH Fakten" in AI and "unzuverlässiger Inhalt" in AI and '"supported"' in AI)
check("fallback pings team and stops repeated escalation", "notified_roles" in TICKET and "roles=True" in TICKET and "escalated" in AI)
check("AI output cannot ping users or everyone", "AllowedMentions.none()" in TICKET and "@\\u200b" in AI)
check("Discord responses use Components V2", "Panel(" in TICKET and "view=view" in TICKET)
check("ticket histories are not persisted", "message.content" in TICKET and "ticket_ai_usage" in AI and "ticket_ai_messages" not in AI)
check("server scan covers complete dashboard data and 30 days of admin messages", "config_transfer.export_guild" in SCAN and "DASHBOARD-EINSTELLUNGEN" in SCAN and "for offset in range" in SCAN and "timedelta(days=30)" in SCAN and "administrator" in SCAN and "guild.owner_id" in SCAN)
check("scan visits every bot-readable channel and thread without a message limit", "text_channels" in SCAN and "archived_threads" in SCAN and "guild, \"threads\"" in SCAN and "history(limit=None" in SCAN and "read_message_history" in SCAN)
check("scan redacts credentials and resists prompt injection", "_SECRET_PATTERNS" in SCAN and "Prompt-Injection" in SCAN and "GEHEIMNIS ENTFERNT" in SCAN)
check("generated knowledge is previewed before replacement", "Server lesen lassen" in PANEL and "Vorschau des automatisch erstellten Wissens" in PANEL and "Geprüften Entwurf als TXT übernehmen" in PANEL)
check("current txt is viewable and editable", "Aktuelle Wissensdatei ansehen und bearbeiten" in PANEL and "knowledgeText" in PANEL and "Text speichern" in PANEL)
check("long scan runs as a progress job", "ticket_ai_scan_jobs" in AI and "asyncio.create_task" in API and "getTicketAiScan" in PANEL)
check("all admitted dashboard users may manage AI knowledge", 'if (rest[1] === "ai") return { ok: true }' in BFF and "verifyGuildAccess(guildId)" in BFF)

print(f"\n{len(failures)} Fehler")
for failure in failures: print(f"  - {failure}")
raise SystemExit(bool(failures))
