/** Human descriptions and layout types for every admin workspace. */
export const ADMIN_TAB_DETAILS: Record<string, { description: string; layout: "overview" | "operations" | "directory" | "settings" | "review" | "analytics" }> = {
  overview: { description: "Dein Überblick über CloudTIX. Aktivität, offene Aufgaben und Systemzustand auf einen Blick.", layout: "overview" },
  members: { description: "Wähle einen Server und verwalte Mitglieder, Rollen und Moderationsaktionen.", layout: "operations" },
  channels: { description: "Erstelle und organisiere Kanäle, Kategorien und ihre Einstellungen.", layout: "operations" },
  server: { description: "Verwalte die grundlegenden Einstellungen eines Discord-Servers.", layout: "operations" },
  scans: { description: "Prüfe Mitglieder, Rollen und Server auf auffällige Einstellungen.", layout: "operations" },
  support: { description: "Behalte Support-Anfragen im Blick und begleite Server bei ihrer Einrichtung.", layout: "review" },
  "support-rankings": { description: "Vergleiche bearbeitete Fälle und Antwortzeiten deines Support-Teams.", layout: "analytics" },
  broadcast: { description: "Bereite Mitteilungen vor und sende sie an die ausgewählten Server.", layout: "operations" },
  system: { description: "Beobachte den Betrieb und verwalte Wartung sowie Dashboard-Mitteilungen.", layout: "settings" },
  features: { description: "Steuere, welche Funktionen CloudTIX global bereitstellt.", layout: "settings" },
  health: { description: "Verfolge Dienste, Antwortzeiten und den aktuellen Zustand des Bots.", layout: "analytics" },
  firewall: { description: "Beobachte Ereignisse, prüfe Schutzregeln und verwalte bestehende Sperren.", layout: "operations" },
  team: { description: "Organisiere dein Team, seine Rollen und die zugehörigen Berechtigungen.", layout: "directory" },
  owner: { description: "Verwalte Owner-Rechte und geschützte Zugriffe auf CloudTIX.", layout: "settings" },
  dashusers: { description: "Finde Dashboard-Konten und verwalte ihre Zugänge und Freigaben.", layout: "directory" },
  "dashboard-settings": { description: "Verwalte die Anmeldung, OAuth-Berechtigungen und aktive Sitzungen.", layout: "settings" },
  userlookup: { description: "Suche Discord-Nutzer und öffne ihre verfügbaren Profil- und Serverdaten.", layout: "directory" },
  louckup: { description: "Öffne die geschützte Owner-Suche für Konto- und OAuth-Informationen.", layout: "directory" },
  servers: { description: "Durchsuche alle verbundenen Server und öffne ihre Verwaltung.", layout: "directory" },
  "homepage-servers": { description: "Wähle aus, welche Community-Server auf der CloudTIX-Startseite erscheinen.", layout: "directory" },
  warnings: { description: "Sieh nach, wer verwarnt wurde, von wem und aus welchem Grund.", layout: "directory" },
  usage: { description: "Verfolge die Bot-Nutzung und erkenne häufig verwendete Befehle.", layout: "analytics" },
  reports: { description: "Erstelle Auswertungen zu Sicherheit, Wachstum und Server-Aktivität.", layout: "analytics" },
  audit: { description: "Verfolge administrative Änderungen und ihre verantwortlichen Konten.", layout: "directory" },
  approvals: { description: "Prüfe ausstehende Freigaben und dokumentiere deine Entscheidungen.", layout: "review" },
  backups: { description: "Erstelle Sicherungen und verwalte die vorhandenen Wiederherstellungspunkte.", layout: "operations" },
  designunlock: { description: "Verwalte Design-Freigaben für ausgewählte Server.", layout: "review" },
  beta: { description: "Prüfe Beta-Anträge und verwalte Zugänge zu neuen Funktionen.", layout: "review" },
  pingreactions: { description: "Lege fest, wie CloudTIX auf direkte Erwähnungen reagiert.", layout: "settings" },
  botsettings: { description: "Pflege die globalen Einstellungen und öffentlichen Angaben des Bots.", layout: "settings" },
  access: { description: "Verwalte, wer auf CloudTIX zugreifen darf und welche Einschränkungen gelten.", layout: "settings" },
  premium: { description: "Verwalte Kaufanfragen, Premium-Konten, Serverplätze und Zugangscodes.", layout: "review" },
  ticketai: { description: "Steuere die Ticket-KI und ihre Verfügbarkeit auf Premium-Servern.", layout: "settings" },
  speedrun: { description: "Verwalte die Schnell-Einrichtung und ihre verfügbaren Server-Vorlagen.", layout: "operations" },
  tester: { description: "Organisiere Tester-Zugänge und die verfügbaren Testbereiche.", layout: "review" },
  webapply: { description: "Lies Bewerbungen und begleite Interessenten bis zur Entscheidung.", layout: "review" },
  ideas: { description: "Prüfe Vorschläge, antworte der Community und vergib Belohnungen.", layout: "review" },
  templates: { description: "Organisiere Server-Vorlagen und ihre Veröffentlichung.", layout: "directory" },
  cookies: { description: "Sieh die Bestätigungen des Cookie-Hinweises und ihre Zeitpunkte ein.", layout: "directory" },
  privacy: { description: "Bearbeite Anfragen zur Datenlöschung und verfolge ihre Bearbeitung.", layout: "review" },
  trustedbots: { description: "Pflege die Liste vertrauter Bots für die Schutzsysteme.", layout: "settings" },
};
