"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  Activity, AlertTriangle, Ban, Bot, BrainCircuit, CheckCircle2, Clock3,
  Gauge, Globe2, KeyRound, Loader2, LockKeyhole, Plus, RefreshCw, Save, ChevronDown,
  Search, Shield, ShieldCheck, Trash2, Undo2, UserRoundX, Wifi, X, Zap, Settings2, Download, Eraser, EyeOff, BarChart3, Power, History, GitCompare, RotateCcw,
} from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/api";
import { cn } from "@/lib/utils";

type Tab = "overview" | "bans" | "trusted" | "protection" | "events" | "analytics" | "audit" | "operations" | "diagnostics";
type Rule = { id:number; kind:string; value:string; note:string; created_at:number; expires_at:number|null; created_by:string; enabled:number; priority:number };
type Event = { id:number; ip:string; actor_id?:string; method:string; path:string; category:string; severity:string; created_at:number; request_count:number; blocked:number; note?:string; ai_report?:string };

const fmt = (seconds:number) => new Date(seconds * 1000).toLocaleString("de-DE");
const ruleNames:Record<string,string> = {
  block:"IP/CIDR gesperrt", allow:"IP/CIDR erlaubt", user_block:"Nutzer gesperrt",
  user_allow:"Nutzer erlaubt", user_agent:"User-Agent", path:"Pfad", country:"Land", method:"HTTP-Methode",
};

export function FirewallPanel() {
  const [data,setData] = useState<any>(null);
  const [tab,setTab] = useState<Tab>("overview");
  const [loading,setLoading] = useState(true);
  const [busy,setBusy] = useState(false);
  const [query,setQuery] = useState("");
  const [confirmEvent,setConfirmEvent] = useState<Event|null>(null);
  const [report,setReport] = useState<any>(null);
  const [diagnostics,setDiagnostics] = useState<any>(null);
  const [inspection,setInspection] = useState<any>(null);
  const [inspect,setInspect] = useState({ip:"",actor_id:"",path:"/dashboard",country:"",user_agent:"",method:"GET"});
  const [newRule,setNewRule] = useState({kind:"block",value:"",note:"",minutes:0});
  const [quickUnban,setQuickUnban] = useState({kind:"ip",value:""});
  const [operation,setOperation] = useState<{type:"bulk"|"reset";value:string;title:string;text:string}|null>(null);
  const [eventFilter,setEventFilter] = useState("all");
  const [categoryFilter,setCategoryFilter] = useState("all");
  const [selectedEvent,setSelectedEvent] = useState<Event|null>(null);
  const [selectedRule,setSelectedRule] = useState<Rule|null>(null);
  const [ruleEdit,setRuleEdit] = useState({minutes:0,note:"",enabled:true,priority:100});
  const [snapshots,setSnapshots] = useState<any[]>([]);
  const [snapshotName,setSnapshotName] = useState("");
  const [snapshotAction,setSnapshotAction] = useState<{id:number;name:string;type:"restore"|"delete"}|null>(null);
  const [refreshSeconds,setRefreshSeconds] = useState("15");
  const [ruleFilter,setRuleFilter] = useState("all");
  const [eventNote,setEventNote] = useState("");
  const [cloneValue,setCloneValue] = useState("");
  const [audit,setAudit] = useState<any>(null);
  const [emergencyMinutes,setEmergencyMinutes] = useState("30");
  const [auditEntries,setAuditEntries] = useState<any[]>([]);
  const [comparison,setComparison] = useState<any>(null);
  const [selfTest,setSelfTest] = useState<any>(null);
  const [rollbackEntry,setRollbackEntry] = useState<any>(null);
  const [rollbackReason,setRollbackReason] = useState("");

  const load = useCallback(async (silent=false) => {
    if (!silent) setLoading(true);
    try { const [overview,saved,auditLog]=await Promise.all([api.getFirewallOverview(),api.getFirewallSnapshots(),api.getFirewallAudit()]); setData(overview); setSnapshots(saved.snapshots||[]); setAuditEntries(auditLog.entries||[]); }
    catch (error:any) { toast.error(error?.message || "Firewall konnte nicht geladen werden."); }
    finally { setLoading(false); }
  },[]);

  useEffect(() => { void load(); },[load]);
  useEffect(() => { const seconds=Number(refreshSeconds); if(!seconds)return; const timer=setInterval(() => void load(true),seconds*1000); return () => clearInterval(timer); },[load,refreshSeconds]);

  const rules:Rule[] = data?.rules || [];
  const visibleRules=rules.filter(rule=>ruleFilter==="all"||(ruleFilter==="active"?Boolean(rule.enabled):ruleFilter==="disabled"?!rule.enabled:rule.kind===ruleFilter));
  const events:Event[] = useMemo(() => (data?.events || []).filter((event:Event) => {
    const search=`${event.ip} ${event.actor_id || ""} ${event.path} ${event.category}`.toLowerCase().includes(query.toLowerCase());
    const state=eventFilter==="all" || (eventFilter==="blocked"?Boolean(event.blocked):!event.blocked);
    const category=categoryFilter==="all" || event.category===categoryFilter;
    return search && state && category;
  }),[data,query,eventFilter,categoryFilter]);
  const settings = data?.settings || {};

  const saveSettings = async () => {
    setBusy(true);
    try { await api.updateFirewallSettings(settings); toast.success("Schutzprofil gespeichert."); await load(true); }
    catch (error:any) { toast.error(error?.message || "Einstellungen konnten nicht gespeichert werden."); }
    finally { setBusy(false); }
  };
  const createRule = async () => {
    if (!newRule.value.trim()) return toast.error("Bitte einen Regelwert eingeben.");
    setBusy(true);
    try { await api.addFirewallRule(newRule); setNewRule({...newRule,value:"",note:""}); toast.success("Regel aktiviert."); await load(true); }
    catch (error:any) { toast.error(error?.message || "Regel konnte nicht aktiviert werden."); }
    finally { setBusy(false); }
  };
  const removeRule = async (rule:Rule) => {
    setBusy(true);
    try { await api.deleteFirewallRule(rule.id); toast.success(`${ruleNames[rule.kind] || "Regel"} aufgehoben.`); await load(true); }
    catch (error:any) { toast.error(error?.message || "Entsperren fehlgeschlagen."); }
    finally { setBusy(false); }
  };
  const unban = async () => {
    setBusy(true);
    try { await api.unbanFirewall(quickUnban); toast.success("Sperre vollständig entfernt."); setQuickUnban({...quickUnban,value:""}); await load(true); }
    catch (error:any) { toast.error(error?.message || "Keine passende Sperre gefunden."); }
    finally { setBusy(false); }
  };
  const stopAttack = async () => {
    if (!confirmEvent) return;
    setBusy(true);
    try { await api.stopFirewallIncident(confirmEvent.id); toast.success("Quelle manuell gesperrt."); setConfirmEvent(null); await load(true); }
    catch (error:any) { toast.error(error?.message || "Diese Quelle darf nicht gesperrt werden."); }
    finally { setBusy(false); }
  };
  const acknowledge = async (event:Event) => {
    setBusy(true);
    try { await api.acknowledgeFirewallIncident(event.id); setSelectedEvent(null); toast.success("Alarm geschlossen – niemand wurde gesperrt."); await load(true); }
    catch (error:any) { toast.error(error?.message || "Alarm konnte nicht geschlossen werden."); }
    finally { setBusy(false); }
  };
  const trustEvent = async (event:Event,scope:"ip"|"user") => {
    setBusy(true);
    try { await api.trustFirewallIncident(event.id,scope); setSelectedEvent(null); toast.success(scope==="ip"?"IP als sicher markiert und entsperrt.":"Nutzer als sicher markiert und entsperrt."); await load(true); }
    catch (error:any) { toast.error(error?.message || "Als sicher markieren fehlgeschlagen."); }
    finally { setBusy(false); }
  };
  const saveRuleEdit = async () => {
    if (!selectedRule) return;
    setBusy(true);
    try { await api.editFirewallRule(selectedRule.id,ruleEdit); setSelectedRule(null); toast.success("Regel aktualisiert."); await load(true); }
    catch (error:any) { toast.error(error?.message || "Regel konnte nicht geändert werden."); }
    finally { setBusy(false); }
  };
  const analyze = async (event:Event) => {
    setBusy(true);
    try { setReport(await api.analyzeFirewallIncident(event.id)); }
    catch (error:any) { toast.error(error?.message || "Grok-Bericht nicht verfügbar."); }
    finally { setBusy(false); }
  };
  const runInspection = async () => {
    setBusy(true);
    try { setInspection(await api.inspectFirewall(inspect)); }
    catch (error:any) { toast.error(error?.message || "Prüfung fehlgeschlagen."); }
    finally { setBusy(false); }
  };
  const runDiagnostics = async () => {
    setBusy(true);
    try { const [diagnostic,auditResult]=await Promise.all([api.getFirewallDiagnostics(),api.getFirewallSafetyAudit()]); setDiagnostics(diagnostic); setAudit(auditResult); toast.success("Eigene API und Sicherheitsprofil geprüft."); }
    catch (error:any) { toast.error(error?.message || "Diagnose fehlgeschlagen."); }
    finally { setBusy(false); }
  };
  const saveEventNote = async () => { if(!selectedEvent||!eventNote.trim())return;setBusy(true);try{await api.annotateFirewallEvent(selectedEvent.id,eventNote);setEventNote("");setSelectedEvent(null);toast.success("Ereignisnotiz gespeichert.");await load(true)}catch(error:any){toast.error(error?.message||"Notiz konnte nicht gespeichert werden.")}finally{setBusy(false)} };
  const cloneRule = async () => { if(!selectedRule||!cloneValue.trim())return;setBusy(true);try{await api.cloneFirewallRule(selectedRule.id,{value:cloneValue,minutes:ruleEdit.minutes});setCloneValue("");setSelectedRule(null);toast.success("Regelvorlage auf neuen Wert kopiert.");await load(true)}catch(error:any){toast.error(error?.message||"Regel konnte nicht kopiert werden.")}finally{setBusy(false)} };
  const timedEmergency = async () => {setBusy(true);try{await api.setTimedFirewallEmergency(Number(emergencyMinutes));toast.success(Number(emergencyMinutes)?`Notfallmodus für ${emergencyMinutes} Minuten aktiviert.`:"Notfallmodus beendet.");await load(true)}catch(error:any){toast.error(error?.message||"Notfallmodus konnte nicht geändert werden.")}finally{setBusy(false)} };
  const exportEventsCsv = () => { const quote=(value:any)=>`"${String(value??"").replaceAll('"','""')}"`; const rows=[["Zeit","IP","Nutzer","Methode","Pfad","Kategorie","Blockiert","Notiz"],...events.map(event=>[fmt(event.created_at),event.ip,event.actor_id||"",event.method,event.path,event.category,event.blocked?"Ja":"Nein",event.note||""])]; const blob=new Blob(["\ufeff"+rows.map(row=>row.map(quote).join(";")).join("\n")],{type:"text/csv;charset=utf-8"}); const url=URL.createObjectURL(blob); const link=document.createElement("a");link.href=url;link.download=`firewall-events-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);toast.success("Gefilterte Ereignisse als CSV exportiert."); };
  const applyPreset = async (name:string) => {
    setBusy(true);
    try { await api.applyFirewallPreset(name); toast.success("Schutzprofil übernommen; Laufzeitzähler wurden zurückgesetzt."); await load(true); }
    catch (error:any) { toast.error(error?.message || "Profil konnte nicht angewendet werden."); }
    finally { setBusy(false); }
  };
  const executeOperation = async () => {
    if (!operation) return;
    setBusy(true);
    try {
      const result=operation.type==="reset" ? await api.resetFirewallCounters() : await api.bulkUnbanFirewall(operation.value);
      toast.success(operation.type==="reset"?"Alle flüchtigen Zähler zurückgesetzt.":`${result.removed || 0} Regeln entfernt.`);
      setOperation(null); await load(true);
    } catch (error:any) { toast.error(error?.message || "Aktion fehlgeschlagen."); }
    finally { setBusy(false); }
  };
  const exportConfig = async () => {
    setBusy(true);
    try { const config=await api.exportFirewallConfiguration(); const blob=new Blob([JSON.stringify(config,null,2)],{type:"application/json"}); const url=URL.createObjectURL(blob); const link=document.createElement("a"); link.href=url; link.download=`firewall-config-${new Date().toISOString().slice(0,10)}.json`; link.click(); URL.revokeObjectURL(url); toast.success("Konfiguration exportiert – ohne Ereignisse und IP-Verlauf."); }
    catch (error:any) { toast.error(error?.message || "Export fehlgeschlagen."); }
    finally { setBusy(false); }
  };
  const createSnapshot = async () => {
    setBusy(true);
    try { await api.createFirewallSnapshot(snapshotName || "Manuelle Sicherung"); setSnapshotName(""); toast.success("Wiederherstellungspunkt erstellt."); await load(true); }
    catch (error:any) { toast.error(error?.message || "Sicherung fehlgeschlagen."); }
    finally { setBusy(false); }
  };
  const executeSnapshotAction = async () => {
    if (!snapshotAction) return;
    setBusy(true);
    try { if(snapshotAction.type==="restore") await api.restoreFirewallSnapshot(snapshotAction.id); else await api.deleteFirewallSnapshot(snapshotAction.id); toast.success(snapshotAction.type==="restore"?"Firewall-Konfiguration wiederhergestellt.":"Sicherung gelöscht."); setSnapshotAction(null); await load(true); }
    catch (error:any) { toast.error(error?.message || "Sicherungsaktion fehlgeschlagen."); }
    finally { setBusy(false); }
  };
  const compareSnapshot = async (id:number) => { setBusy(true);try{setComparison(await api.compareFirewallSnapshot(id))}catch(error:any){toast.error(error?.message||"Vergleich fehlgeschlagen.")}finally{setBusy(false)} };
  const runSelfTest = async () => { setBusy(true);try{const result=await api.runFirewallSelfProtectionTest();setSelfTest(result);toast.success(result.passed?"Alle Self-Protection-Tests bestanden.":"Mindestens ein Self-Protection-Test ist fehlgeschlagen.")}catch(error:any){toast.error(error?.message||"Self-Test fehlgeschlagen.")}finally{setBusy(false)} };
  const rollbackAudit = async () => { if(!rollbackEntry)return;setBusy(true);try{await api.rollbackFirewallAudit(rollbackEntry.id,rollbackReason||`Rollback Audit #${rollbackEntry.id}`);setRollbackEntry(null);setRollbackReason("");toast.success("Einzelne Änderung rückgängig gemacht.");await load(true)}catch(error:any){toast.error(error?.message||"Rollback fehlgeschlagen.")}finally{setBusy(false)} };

  if (loading) return <div className="grid min-h-80 place-items-center"><Loader2 className="h-7 w-7 animate-spin text-cyan-400"/></div>;

  return <div className={cn("space-y-5",busy && "pointer-events-none opacity-75")}>
    <header className="relative overflow-hidden rounded-3xl border border-cyan-500/20 bg-[#101116] p-6 sm:p-8">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_90%_0%,rgba(6,182,212,.16),transparent_42%)]"/>
      <div className="relative flex flex-col gap-5 lg:flex-row lg:items-center">
        <span className="grid h-16 w-16 place-items-center rounded-2xl border border-cyan-400/20 bg-cyan-400/10"><Shield className="h-8 w-8 text-cyan-300"/></span>
        <div className="flex-1"><p className="text-xs font-black uppercase tracking-[.22em] text-cyan-300">Firewall Control Center</p><h2 className="mt-1 text-3xl font-black text-white">Sicher blockieren, niemals raten</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Owner, eigene Netze und interne Bot-Aufrufe haben Vorrang vor allen Sperren. Automatische Sperren sind standardmäßig aus; Alarme bleiben sichtbar und jede manuelle Sperre ist rückgängig.</p></div>
        <div className="flex gap-2"><Status active={settings.enabled} label={settings.enabled?"Schutz aktiv":"Schutz aus"}/><Status active={!settings.auto_block_enabled} label={settings.auto_block_enabled?"Auto-Bann aktiv":"Nur Alarm"}/></div>
      </div>
    </header>

    <div className="grid grid-cols-2 gap-3 lg:grid-cols-5">
      <Metric icon={Activity} label="Ereignisse · 24h" value={data.stats.events_24h}/>
      <Metric icon={AlertTriangle} label="Alarme · 24h" value={data.stats.alarms_24h}/>
      <Metric icon={Ban} label="Blockiert · 24h" value={data.stats.blocked_24h}/>
      <Metric icon={UserRoundX} label="Aktive Sperren" value={data.stats.manual_bans}/>
      <Metric icon={Globe2} label="Quellen · 24h" value={data.stats.unique_ips_24h}/>
    </div>

    <nav className="flex gap-1 overflow-x-auto rounded-2xl border border-slate-800 bg-[#131318] p-1.5">
      {([
        ["overview","Übersicht",ShieldCheck],["bans","Sperren & Entsperren",UserRoundX],
        ["trusted","Vertrauen",KeyRound],["protection","Schutzprofil",Gauge],
        ["events","Ereignisse",Clock3],["analytics","Analyse",BarChart3],["audit","Audit-Log",History],["operations","Werkzeuge",Settings2],["diagnostics","API-Diagnose",Bot],
      ] as [Tab,string,any][]).map(([id,label,Icon]) => <button key={id} onClick={() => setTab(id)} className={cn("flex shrink-0 items-center gap-2 rounded-xl px-4 py-3 text-xs font-bold transition",tab===id?"bg-cyan-500/10 text-cyan-200":"text-slate-500 hover:bg-white/[.03] hover:text-white")}><Icon className="h-4 w-4"/>{label}</button>)}
    </nav>
    <div className="flex items-center justify-end gap-2"><span className="text-xs text-slate-600">Live-Aktualisierung</span><div className="w-44"><CustomSelect value={refreshSeconds} onChange={setRefreshSeconds} title="Aktualisierungsintervall" options={[{value:"0",label:"Aus"},{value:"5",label:"Alle 5 Sekunden"},{value:"15",label:"Alle 15 Sekunden"},{value:"30",label:"Alle 30 Sekunden"},{value:"60",label:"Jede Minute"}]}/></div></div>

    {tab==="overview" && <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]">
      <Panel title="Aktive Warnungen" icon={Zap}>{data.active_incidents.length ? <div className="space-y-2">{data.active_incidents.slice(0,12).map((event:Event) => <EventRow key={event.id} event={event} onStop={setConfirmEvent} onAnalyze={analyze} onAcknowledge={acknowledge}/>)}</div> : <Empty text="Keine laufenden Warnungen. Normale Aufrufe werden nicht protokolliert."/>}</Panel>
      <Panel title="Sicherheitsgarantien" icon={ShieldCheck}><div className="space-y-3"><Guarantee title="Owner-Schutz" text="Konfigurierte Owner-IDs können nie durch Firewall-Regeln gesperrt werden."/><Guarantee title="Self-Protection" text="Firewall-Verwaltung und /firewall/check prüfen oder blockieren sich niemals selbst."/><Guarantee title="Interne API" text="Lokale Bot-Aufrufe werden weder gezählt noch als Angriff gespeichert."/><Guarantee title="Keine KI-Entscheidungen" text="Grok schreibt nur Berichte; Erkennung und Aktionen bleiben deterministisch und manuell."/></div></Panel>
    </div>}

    {tab==="bans" && <div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]">
      <div className="space-y-4"><Panel title="Manuelle Regel" icon={Plus}><Field label="Regelart"><CustomSelect value={newRule.kind} onChange={kind=>setNewRule({...newRule,kind})} title="Regelart auswählen" options={[{value:"block",label:"IP oder CIDR sperren"},{value:"user_block",label:"Discord-Nutzer sperren"},{value:"allow",label:"IP oder CIDR immer erlauben"},{value:"user_allow",label:"Discord-Nutzer immer erlauben"},{value:"country",label:"Land sperren"},{value:"user_agent",label:"User-Agent sperren"},{value:"path",label:"Pfad-Muster sperren"},{value:"method",label:"HTTP-Methode sperren"}]}/></Field><Field label="Wert"><input className="input" value={newRule.value} onChange={e=>setNewRule({...newRule,value:e.target.value})} placeholder={newRule.kind.includes("user_")?"Discord-Nutzer-ID":newRule.kind==="country"?"DE":"IP, CIDR oder Muster"}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Dauer · Minuten"><input className="input" type="number" min="0" value={newRule.minutes} onChange={e=>setNewRule({...newRule,minutes:Number(e.target.value)})}/></Field><Field label="Notiz"><input className="input" value={newRule.note} onChange={e=>setNewRule({...newRule,note:e.target.value})} placeholder="Grund"/></Field></div><p className="mt-3 text-xs text-slate-600">0 Minuten bedeutet dauerhaft. Owner-IDs sowie eigene und vertrauenswürdige Netze lehnt das Backend immer ab.</p><button onClick={createRule} className="primary mt-4 w-full"><LockKeyhole className="h-4 w-4"/>Regel aktivieren</button></Panel>
      <Panel title="Schnell entsperren" icon={Undo2}><div className="grid grid-cols-[130px_1fr] gap-2"><CustomSelect value={quickUnban.kind} onChange={kind=>setQuickUnban({...quickUnban,kind})} title="Entsperrtyp auswählen" options={[{value:"ip",label:"IP/CIDR"},{value:"user",label:"Nutzer-ID"}]}/><input className="input" value={quickUnban.value} onChange={e=>setQuickUnban({...quickUnban,value:e.target.value})} placeholder="Exakter gesperrter Wert"/></div><button onClick={unban} className="secondary mt-3 w-full"><Undo2 className="h-4 w-4"/>Sperre entfernen</button></Panel></div>
      <Panel title="Regeln verwalten" icon={Ban}><div className="mb-4"><CustomSelect value={ruleFilter} onChange={setRuleFilter} title="Firewall-Regeln filtern" options={[{value:"all",label:"Alle Regeln"},{value:"active",label:"Nur aktive Regeln"},{value:"disabled",label:"Nur deaktivierte Regeln"},{value:"block",label:"IP/CIDR-Sperren"},{value:"user_block",label:"Nutzersperren"},{value:"allow",label:"IP-Allowlist"},{value:"user_allow",label:"Nutzer-Allowlist"},{value:"path",label:"Pfadregeln"},{value:"method",label:"Methodenregeln"}]}/></div>{visibleRules.length ? <div className="space-y-2">{visibleRules.map(rule => <RuleRow key={rule.id} rule={rule} remove={removeRule} edit={rule=>{setSelectedRule(rule);setRuleEdit({minutes:rule.expires_at?Math.max(1,Math.ceil((rule.expires_at-Date.now()/1000)/60)):0,note:rule.note||"",enabled:Boolean(rule.enabled),priority:rule.priority||100})}}/>)}</div> : <Empty text="Keine manuellen Regeln aktiv."/>}</Panel>
    </div>}

    {tab==="trusted" && <div className="grid gap-4 lg:grid-cols-2">
      <Panel title="Vertrauenswürdige Netze" icon={Wifi}><p className="mb-3 text-sm leading-6 text-slate-400">Diese Netze werden vor jeder Blockregel geprüft und niemals gezählt, geflaggt oder gesperrt.</p><textarea className="input min-h-44 font-mono" value={(settings.trusted_networks||[]).join("\n")} onChange={e=>setData({...data,settings:{...settings,trusted_networks:e.target.value.split(/\n|,/).map(v=>v.trim()).filter(Boolean)}})}/><button onClick={saveSettings} className="primary mt-4"><Save className="h-4 w-4"/>Netze speichern</button></Panel>
      <Panel title="Regel sicher testen" icon={Search}><p className="mb-3 text-sm text-slate-400">Dry-Run: erzeugt kein Ereignis, erhöht keinen Zähler und sperrt niemanden.</p><div className="grid gap-3 sm:grid-cols-2"><Field label="IP"><input className="input" value={inspect.ip} onChange={e=>setInspect({...inspect,ip:e.target.value})} placeholder="203.0.113.10"/></Field><Field label="Discord-Nutzer-ID"><input className="input" value={inspect.actor_id} onChange={e=>setInspect({...inspect,actor_id:e.target.value})}/></Field><Field label="Pfad"><input className="input" value={inspect.path} onChange={e=>setInspect({...inspect,path:e.target.value})}/></Field><Field label="Land"><input className="input" value={inspect.country} onChange={e=>setInspect({...inspect,country:e.target.value})}/></Field><Field label="HTTP-Methode"><CustomSelect value={inspect.method} onChange={method=>setInspect({...inspect,method})} title="HTTP-Methode auswählen" options={["GET","POST","PUT","PATCH","DELETE","OPTIONS","HEAD"].map(value=>({value,label:value}))}/></Field></div><button onClick={runInspection} className="secondary mt-4"><Search className="h-4 w-4"/>Ohne Aktion prüfen</button>{inspection && <Result allowed={inspection.allowed} title={inspection.allowed?"Würde erlaubt":"Würde blockiert"} text={`${inspection.reason}${inspection.rule?` · Regel #${inspection.rule.id}`:""}`}/>}</Panel>
    </div>}

    {tab==="protection" && <Panel title="Konservatives Schutzprofil" icon={Gauge}>
      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><Toggle label="Firewall aktiv" text="Explizite Regeln und Alarme anwenden" value={settings.enabled} set={v=>setData({...data,settings:{...settings,enabled:v}})}/><Toggle label="Automatisch sperren" text="Standardmäßig aus; erst nach mehreren Bestätigungen" value={settings.auto_block_enabled} danger set={v=>setData({...data,settings:{...settings,auto_block_enabled:v}})}/><Toggle label="Scanner erkennen" text="Bekannte offensive Scanner blockieren" value={settings.block_bad_bots} set={v=>setData({...data,settings:{...settings,block_bad_bots:v}})}/><Toggle label="Notfallmodus" text="Nur bei einem bestätigten Angriff einschalten" value={settings.emergency_mode} danger set={v=>setData({...data,settings:{...settings,emergency_mode:v}})}/></div>
      <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><NumberField label="Anfragen pro Minute" value={settings.requests_per_minute} set={v=>setData({...data,settings:{...settings,requests_per_minute:v}})}/><NumberField label="Burst in 10 Sekunden" value={settings.burst_10_seconds} set={v=>setData({...data,settings:{...settings,burst_10_seconds:v}})}/><NumberField label="Bestätigungen vor Auto-Sperre" value={settings.confirmations_required} set={v=>setData({...data,settings:{...settings,confirmations_required:v}})}/><NumberField label="Bestätigungsfenster · Sekunden" value={settings.confirmation_window_seconds} set={v=>setData({...data,settings:{...settings,confirmation_window_seconds:v}})}/><NumberField label="Automatische Sperre · Minuten" value={settings.auto_block_minutes} set={v=>setData({...data,settings:{...settings,auto_block_minutes:v}})}/><NumberField label="Notfalllimit pro Minute" value={settings.emergency_rpm} set={v=>setData({...data,settings:{...settings,emergency_rpm:v}})}/></div>
      <Field label="Geschützte Pfad-Präfixe · eine Zeile je Pfad"><textarea className="input min-h-24 font-mono" value={(settings.protected_paths||[]).join("\n")} onChange={e=>setData({...data,settings:{...settings,protected_paths:e.target.value.split(/\n|,/).map(v=>v.trim()).filter(Boolean)}})}/></Field>
      <Field label="Länder-Blockliste · ISO-Codes"><input className="input" value={(settings.country_blocklist||[]).join(", ")} onChange={e=>setData({...data,settings:{...settings,country_blocklist:e.target.value.split(",").map(v=>v.trim()).filter(Boolean)}})}/></Field>
      <div className="mt-4 rounded-xl border border-amber-500/20 bg-amber-500/[.05] p-4 text-xs leading-5 text-amber-200">Eine Grenzwertüberschreitung ist zunächst nur ein Alarm. Ohne „Automatisch sperren“ wird unabhängig von der Anzahl der Alarme niemals automatisch eine Regel erstellt.</div><button onClick={saveSettings} className="primary mt-4"><Save className="h-4 w-4"/>Schutzprofil speichern</button>
    </Panel>}

    {tab==="events" && <Panel title="90-Tage-Ereignisverlauf" icon={Clock3}><div className="mb-4 grid gap-2 xl:grid-cols-[1fr_180px_210px_auto_auto]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-600"/><input className="input pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="IP, Nutzer-ID, Pfad oder Kategorie suchen"/></div><CustomSelect value={eventFilter} onChange={setEventFilter} title="Ereignisstatus filtern" options={[{value:"all",label:"Alle Ereignisse"},{value:"alarm",label:"Nur Alarme"},{value:"blocked",label:"Nur Blockierungen"}]}/><CustomSelect value={categoryFilter} onChange={setCategoryFilter} title="Kategorie filtern" options={[{value:"all",label:"Alle Kategorien"},...Array.from(new Set((data.events||[]).map((event:Event)=>event.category))).map(value=>({value:String(value),label:String(value)}))]}/><button onClick={()=>load()} className="secondary"><RefreshCw className="h-4 w-4"/></button><button onClick={exportEventsCsv} className="secondary"><Download className="h-4 w-4"/>CSV</button></div><p className="mb-3 text-xs text-slate-600">{events.length} von {(data.events||[]).length} Ereignissen sichtbar</p><div className="space-y-2">{events.map(event => <EventRow key={event.id} event={event} onStop={setConfirmEvent} onAnalyze={analyze} onAcknowledge={acknowledge} onDetails={event=>{setSelectedEvent(event);setEventNote("")}}/>)}</div></Panel>}

    {tab==="analytics" && <div className="space-y-4"><div className="grid gap-4 xl:grid-cols-2"><Panel title="Ereignisse nach Stunde" icon={BarChart3}><MiniBars items={(data.hourly||[]).map((item:any)=>({label:String(item.hour).slice(11),value:item.count,secondary:item.blocked}))}/></Panel><Panel title="Kategorien" icon={Activity}><RankList items={(data.top_categories||[]).map((item:any)=>({label:item.category,value:item.count}))}/></Panel><Panel title="Häufigste Pfade" icon={Search}><RankList items={(data.top_paths||[]).map((item:any)=>({label:item.path,value:item.count,meta:`${item.blocked||0} blockiert`}))}/></Panel><Panel title="Länder und Methoden" icon={Globe2}><div className="grid gap-5 sm:grid-cols-2"><RankList items={(data.top_countries||[]).map((item:any)=>({label:item.country,value:item.count}))}/><RankList items={(data.top_methods||[]).map((item:any)=>({label:item.method,value:item.count}))}/></div></Panel></div><div className="grid gap-3 sm:grid-cols-3"><Metric icon={Activity} label="Aktuell beobachtete Quellen" value={data.runtime?.tracked_sources}/><Metric icon={AlertTriangle} label="Ausstehende Bestätigungen" value={data.runtime?.pending_confirmations}/><Metric icon={Power} label="Deaktivierte Regeln" value={data.stats?.disabled_rules}/></div></div>}

    {tab==="audit" && <Panel title="Reversibles Audit-Log" icon={History}><p className="mb-4 text-sm text-slate-400">Zeigt Bearbeiter, Zeitpunkt, Begründung sowie vorherigen und neuen Wert. Regel- und Einstellungsänderungen können einzeln zurückgesetzt werden.</p><div className="space-y-3">{auditEntries.length?auditEntries.map((entry:any)=><div key={entry.id} className="rounded-xl border border-slate-800 p-4"><div className="flex flex-wrap items-center gap-2"><span className="rounded-md bg-cyan-500/10 px-2 py-1 text-[10px] font-black text-cyan-300">{entry.action}</span><span className="text-xs font-bold text-white">{entry.actor||"dashboard"}</span><span className="text-xs text-slate-600">{fmt(entry.created_at)}</span>{entry.rolled_back_at&&<span className="rounded-md bg-amber-500/10 px-2 py-1 text-[10px] font-bold text-amber-300">zurückgesetzt</span>}<span className="ml-auto text-[10px] text-slate-600">#{entry.id}</span></div><p className="mt-2 text-xs text-slate-400">{entry.reason||"Keine Begründung"}</p><div className="mt-3 grid gap-2 md:grid-cols-2"><AuditValue label="Vorher" value={entry.before} color="red"/><AuditValue label="Nachher" value={entry.after} color="green"/></div>{!entry.rolled_back_at&&["rule","setting"].includes(entry.target_type)&&<button onClick={()=>{setRollbackEntry(entry);setRollbackReason("")}} className="secondary mt-3"><RotateCcw className="h-4 w-4"/>Diese Änderung zurücksetzen</button>}</div>):<Empty text="Noch keine protokollierten Firewall-Änderungen."/>}</div></Panel>}

    {tab==="operations" && <div className="space-y-4">
      <Panel title="Vordefinierte Schutzprofile" icon={Gauge}><p className="mb-4 text-sm text-slate-400">Profile ändern ausschließlich die Rate-Erkennung. Manuelle Sperren, Allowlisten und vertrauenswürdige Netze bleiben unverändert.</p><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Preset title="Sehr sicher" text="Nur Alarm · 1200/min · 5 Bestätigungen" color="emerald" action={()=>applyPreset("safe")}/><Preset title="Ausgewogen" text="Nur Alarm · 900/min · 4 Bestätigungen" color="cyan" action={()=>applyPreset("balanced")}/><Preset title="Bewacht" text="Auto aktiv · 700/min · 4 Bestätigungen" color="amber" action={()=>applyPreset("guarded")}/><Preset title="Notfall" text="Auto aktiv · Notfalllimit 120/min" color="red" action={()=>applyPreset("emergency")}/></div></Panel>
      <Panel title="Zeitbegrenzter Notfallmodus" icon={Zap}><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><CustomSelect value={emergencyMinutes} onChange={setEmergencyMinutes} title="Notfall-Dauer auswählen" options={[{value:"0",label:"Notfallmodus sofort beenden"},{value:"15",label:"15 Minuten"},{value:"30",label:"30 Minuten"},{value:"60",label:"1 Stunde"},{value:"120",label:"2 Stunden"},{value:"360",label:"6 Stunden"}]}/><button onClick={timedEmergency} className="danger"><Zap className="h-4 w-4"/>Zeitplan anwenden</button></div><p className="mt-3 text-xs text-slate-600">Der Modus läuft automatisch aus. Owner, interne API und vertrauenswürdige Netze bleiben ausgenommen.</p></Panel>
      <div className="grid gap-4 lg:grid-cols-2"><Panel title="Laufzeit-Werkzeuge" icon={Eraser}><Tool title="Rate-Zähler zurücksetzen" text="Vergisst aktuelle Hits und ausstehende Bestätigungen. Keine Regeln oder Ereignisse werden gelöscht." action={()=>setOperation({type:"reset",value:"",title:"Laufzeitzähler zurücksetzen?",text:"Alle aktuellen Rate-Zähler und Bestätigungen werden verworfen. Dauerhafte Daten bleiben erhalten."})}/><Tool title="Temporäre Sperren entfernen" text="Entfernt ausschließlich Regeln mit Ablaufzeit." action={()=>setOperation({type:"bulk",value:"temporary",title:"Alle temporären Regeln entfernen?",text:"Jede zeitlich begrenzte Regel wird sofort aufgehoben."})}/><Tool title="Automatische Sperren entfernen" text="Entfernt nur Regeln, die von der deterministischen Engine erstellt wurden." action={()=>setOperation({type:"bulk",value:"automatic",title:"Automatische Sperren entfernen?",text:"Manuelle Sperren und Allowlisten bleiben erhalten."})}/></Panel><Panel title="Sicherung und Massenentsperrung" icon={Download}><Tool title="Konfiguration exportieren" text="Lädt Einstellungen und Regeln als JSON herunter. Ereignisse und IP-Verlauf werden nicht exportiert." action={exportConfig}/><Tool title="Alle IP- und Nutzersperren aufheben" text="Allowlisten, Pfad- und Scanner-Regeln bleiben erhalten." action={()=>setOperation({type:"bulk",value:"ip_user",title:"Alle IP- und Nutzersperren aufheben?",text:"Diese Aktion entsperrt sämtliche manuell und automatisch gesperrten IPs und Discord-Nutzer."})}/><Tool title="Alle Verbotsregeln entfernen" text="Entfernt IP, Nutzer, Land, Pfad, User-Agent und Methoden-Sperren. Allowlisten bleiben." danger action={()=>setOperation({type:"bulk",value:"all_denies",title:"Wirklich alle Verbotsregeln entfernen?",text:"Die Firewall bleibt aktiv, besitzt danach aber keine expliziten Verbotsregeln mehr."})}/></Panel></div>
      <Panel title="Wiederherstellungspunkte" icon={Clock3}><div className="flex flex-col gap-2 sm:flex-row"><input className="input flex-1" value={snapshotName} onChange={event=>setSnapshotName(event.target.value)} placeholder="Name der Sicherung, z. B. Vor Notfallmodus"/><button onClick={createSnapshot} className="primary"><Save className="h-4 w-4"/>Aktuellen Stand sichern</button></div><p className="mt-2 text-xs text-slate-600">Bis zu 30 Sicherungen. Enthält Einstellungen und Regeln, aber keine IP-Ereignisse. Vor jeder Wiederherstellung wird automatisch eine Rücksicherung erstellt.</p><div className="mt-4 grid gap-2 md:grid-cols-2">{snapshots.length?snapshots.map(snapshot=><div key={snapshot.id} className="flex items-center gap-3 rounded-xl border border-slate-800 p-3"><Clock3 className="h-4 w-4 text-cyan-300"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-white">{snapshot.name}</p><p className="text-[10px] text-slate-600">{fmt(snapshot.created_at)} · {snapshot.created_by||"Dashboard"}</p></div><button onClick={()=>compareSnapshot(snapshot.id)} className="rounded-lg p-2 text-slate-500 hover:bg-violet-500/10 hover:text-violet-300" title="Mit aktuellem Stand vergleichen"><GitCompare className="h-4 w-4"/></button><button onClick={()=>setSnapshotAction({id:snapshot.id,name:snapshot.name,type:"restore"})} className="rounded-lg p-2 text-slate-500 hover:bg-cyan-500/10 hover:text-cyan-300" title="Wiederherstellen"><Undo2 className="h-4 w-4"/></button><button onClick={()=>setSnapshotAction({id:snapshot.id,name:snapshot.name,type:"delete"})} className="rounded-lg p-2 text-slate-500 hover:bg-red-500/10 hover:text-red-300" title="Löschen"><Trash2 className="h-4 w-4"/></button></div>):<Empty text="Noch keine Wiederherstellungspunkte vorhanden."/>}</div></Panel>
      <Panel title="Top-Quellen der letzten 24 Stunden" icon={Activity}><div className="grid gap-2 md:grid-cols-2">{(data.top_sources||[]).map((source:any)=><div key={source.ip} className="flex items-center justify-between rounded-xl border border-slate-800 p-3"><code className="text-xs text-white">{source.ip}</code><span className="text-xs text-slate-500">{source.count} Ereignisse · {source.blocked||0} blockiert</span></div>)}</div></Panel>
    </div>}

    {tab==="diagnostics" && <div className="grid gap-4 lg:grid-cols-2"><Panel title="Eigene API prüfen" icon={Bot}><p className="text-sm leading-6 text-slate-400">Der Diagnoseaufruf läuft über BFF und FastAPI. Firewall-Verwaltungsrouten sind self-exempt und können sich nicht selbst als <code>blocked_ip</code> markieren.</p><div className="mt-5 flex flex-wrap gap-2"><button onClick={runDiagnostics} className="primary"><Activity className="h-4 w-4"/>Diagnose starten</button><button onClick={runSelfTest} className="secondary"><ShieldCheck className="h-4 w-4"/>Self-Protection testen</button></div>{diagnostics && <Result allowed={diagnostics.status==="healthy"} title="API und Firewall erreichbar" text={`${diagnostics.active_rules} aktive Regeln · ${diagnostics.retention_days} Tage Verlauf · KI-Enforcement: nein`}/>} {audit&&<div className="mt-4 rounded-xl border border-slate-800 p-4"><div className="flex items-center justify-between"><p className="font-black text-white">Sicherheitsprüfung</p><span className={cn("text-xl font-black",audit.score>=80?"text-emerald-300":audit.score>=50?"text-amber-300":"text-red-300")}>{audit.score}/100</span></div><div className="mt-3 space-y-2">{audit.findings.length?audit.findings.map((finding:any,index:number)=><div key={index} className="rounded-lg bg-black/20 p-3"><p className="text-xs font-bold text-amber-300">{finding.title}</p><p className="mt-1 text-[11px] text-slate-500">{finding.detail}</p></div>):<p className="text-xs text-emerald-300">Keine riskanten Einstellungen gefunden.</p>}</div></div>}{selfTest&&<div className="mt-4 space-y-2"><p className={cn("text-sm font-black",selfTest.passed?"text-emerald-300":"text-red-300")}>{selfTest.passed?"Alle Self-Protection-Tests bestanden":"Self-Protection-Fehler erkannt"}</p>{selfTest.cases.map((test:any,index:number)=><div key={index} className="flex items-center justify-between rounded-lg border border-slate-800 p-3"><span className="text-xs text-slate-300">{test.name}</span><span className={test.passed?"text-emerald-300":"text-red-300"}>{test.passed?"Bestanden":"Fehlgeschlagen"}</span></div>)}<p className="text-[10px] text-slate-600">Der Test erstellt keine Regeln und keine Sicherheitsereignisse.</p></div>}</Panel><Panel title="Engine-Status" icon={ShieldCheck}><div className="space-y-3"><StatusLine label="Erkennung" value="Deterministisch"/><StatusLine label="Firewall-Self-Protection" value="Aktiv"/><StatusLine label="Interne lokale API" value="Nicht flaggbar"/><StatusLine label="Automatische Sperren" value={settings.auto_block_enabled?"Aktiv":"Aus – nur Alarm"}/><StatusLine label="Speicherung" value="90 Tage"/></div></Panel></div>}

    {comparison && <Modal close={()=>setComparison(null)}><GitCompare className="h-8 w-8 text-violet-300"/><h3 className="mt-4 text-xl font-black text-white">Konfigurationsvergleich</h3><p className="mt-1 text-sm text-slate-500">Aktuell gegenüber „{comparison.snapshot.name}“ · {comparison.total_changes} Änderungen</p><div className="mt-5 space-y-4"><DiffSection title="Einstellungen geändert" items={comparison.settings} render={(item:any)=><div><p className="font-mono text-xs text-white">{item.key}</p><DiffPair before={item.snapshot} after={item.current}/></div>}/><DiffSection title="Regeln neu im aktuellen Stand" items={comparison.rules_added} render={(item:any)=><DiffBox color="green" text={`${item.kind}: ${item.value}`}/>}/><DiffSection title="Regeln fehlen im aktuellen Stand" items={comparison.rules_removed} render={(item:any)=><DiffBox color="red" text={`${item.kind}: ${item.value}`}/>}/><DiffSection title="Regeln verändert" items={comparison.rules_changed} render={(item:any)=><div><p className="font-mono text-xs text-white">{item.key}</p><DiffPair before={item.snapshot} after={item.current}/></div>}/></div><button onClick={()=>{setSnapshotAction({id:comparison.snapshot.id,name:comparison.snapshot.name,type:"restore"});setComparison(null)}} className="primary mt-5"><Undo2 className="h-4 w-4"/>Kompletten Stand wiederherstellen</button></Modal>}
    {rollbackEntry && <Modal close={()=>setRollbackEntry(null)}><RotateCcw className="h-8 w-8 text-amber-300"/><h3 className="mt-4 text-xl font-black text-white">Einzelne Änderung zurücksetzen?</h3><p className="mt-2 text-sm text-slate-400">Audit #{rollbackEntry.id}: {rollbackEntry.reason}</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><AuditValue label="Aktueller/neuer Wert" value={rollbackEntry.after} color="red"/><AuditValue label="Wird wiederhergestellt" value={rollbackEntry.before} color="green"/></div><Field label="Begründung für den Rollback"><textarea className="input min-h-20" value={rollbackReason} onChange={event=>setRollbackReason(event.target.value)} placeholder="Warum wird diese Änderung zurückgesetzt?"/></Field><div className="mt-6 flex justify-end gap-2"><button onClick={()=>setRollbackEntry(null)} className="secondary">Abbrechen</button><button onClick={rollbackAudit} className="danger"><RotateCcw className="h-4 w-4"/>Änderung zurücksetzen</button></div></Modal>}
    {snapshotAction && <Modal close={()=>setSnapshotAction(null)}><Clock3 className="h-8 w-8 text-amber-300"/><h3 className="mt-4 text-xl font-black text-white">{snapshotAction.type==="restore"?"Konfiguration wiederherstellen?":"Sicherung löschen?"}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{snapshotAction.name}</p><p className="mt-3 text-xs text-slate-500">{snapshotAction.type==="restore"?"Vorher wird automatisch der aktuelle Stand gesichert. Laufzeitzähler werden zurückgesetzt; Sicherheitsereignisse bleiben unverändert.":"Die gespeicherte Sicherung wird dauerhaft entfernt. Aktive Firewall-Regeln ändern sich nicht."}</p><div className="mt-6 flex justify-end gap-2"><button onClick={()=>setSnapshotAction(null)} className="secondary">Abbrechen</button><button onClick={executeSnapshotAction} className={snapshotAction.type==="restore"?"primary":"danger"}>{snapshotAction.type==="restore"?"Sicher wiederherstellen":"Sicherung löschen"}</button></div></Modal>}
    {selectedRule && <Modal close={()=>setSelectedRule(null)}><Settings2 className="h-8 w-8 text-cyan-300"/><h3 className="mt-4 text-xl font-black text-white">Regel #{selectedRule.id} bearbeiten</h3><p className="mt-1 font-mono text-sm text-slate-400">{selectedRule.value}</p><Field label="Neue Dauer in Minuten · 0 = dauerhaft"><input className="input" type="number" min="0" value={ruleEdit.minutes} onChange={event=>setRuleEdit({...ruleEdit,minutes:Number(event.target.value)})}/></Field><Field label="Interne Notiz"><textarea className="input min-h-24" value={ruleEdit.note} onChange={event=>setRuleEdit({...ruleEdit,note:event.target.value})}/></Field><Field label="Priorität · 1 wird zuerst geprüft"><input className="input" type="number" min="1" max="1000" value={ruleEdit.priority} onChange={event=>setRuleEdit({...ruleEdit,priority:Number(event.target.value)})}/></Field><Toggle label="Regel aktiv" text="Deaktivierte Regeln bleiben gespeichert und können später wieder eingeschaltet werden." value={ruleEdit.enabled} set={enabled=>setRuleEdit({...ruleEdit,enabled})}/><div className="mt-5 rounded-xl border border-cyan-500/15 bg-cyan-500/[.03] p-4"><p className="text-xs font-black text-cyan-300">Als Vorlage kopieren</p><div className="mt-2 flex gap-2"><input className="input" value={cloneValue} onChange={event=>setCloneValue(event.target.value)} placeholder="Neuer IP-, Nutzer- oder Regelwert"/><button onClick={cloneRule} className="secondary shrink-0"><Plus className="h-4 w-4"/>Kopieren</button></div></div><div className="mt-6 flex justify-end gap-2"><button onClick={()=>setSelectedRule(null)} className="secondary">Abbrechen</button><button onClick={saveRuleEdit} className="primary"><Save className="h-4 w-4"/>Änderung speichern</button></div></Modal>}
    {selectedEvent && <Modal close={()=>setSelectedEvent(null)}><Activity className="h-8 w-8 text-cyan-300"/><h3 className="mt-4 text-xl font-black text-white">Ereignis #{selectedEvent.id}</h3><div className="mt-4 grid gap-2 sm:grid-cols-2"><StatusLine label="IP-Adresse" value={selectedEvent.ip}/><StatusLine label="Discord-Nutzer" value={selectedEvent.actor_id||"Nicht angemeldet"}/><StatusLine label="Kategorie" value={selectedEvent.category}/><StatusLine label="Zeitpunkt" value={fmt(selectedEvent.created_at)}/></div><div className="mt-3 rounded-xl border border-slate-800 p-3"><p className="text-xs text-slate-500">Anfrage</p><p className="mt-1 break-all font-mono text-sm text-white">{selectedEvent.method} {selectedEvent.path}</p></div><p className="mt-4 text-xs leading-5 text-slate-500">„Als sicher markieren“ schließt den Fehlalarm, entfernt eine entsprechende Sperre und erstellt eine reversible Allowlist-Regel.</p><div className="mt-3 flex gap-2"><input className="input" value={eventNote} onChange={event=>setEventNote(event.target.value)} placeholder="Interne Untersuchungsnotiz hinzufügen"/><button onClick={saveEventNote} className="secondary shrink-0"><Save className="h-4 w-4"/>Notiz</button></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><button onClick={()=>trustEvent(selectedEvent,"ip")} className="primary"><ShieldCheck className="h-4 w-4"/>IP als sicher markieren</button><button disabled={!selectedEvent.actor_id} onClick={()=>trustEvent(selectedEvent,"user")} className="primary disabled:opacity-40"><ShieldCheck className="h-4 w-4"/>Nutzer als sicher markieren</button><button onClick={()=>acknowledge(selectedEvent)} className="secondary"><EyeOff className="h-4 w-4"/>Nur Alarm schließen</button><button onClick={()=>{setConfirmEvent(selectedEvent);setSelectedEvent(null)}} className="danger"><Ban className="h-4 w-4"/>IP sperren</button></div></Modal>}
    {operation && <Modal close={()=>setOperation(null)}><Settings2 className="h-8 w-8 text-amber-300"/><h3 className="mt-4 text-xl font-black text-white">{operation.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{operation.text}</p><p className="mt-3 text-xs text-emerald-300">Owner, interne API und vertrauenswürdige Netze bleiben immer geschützt.</p><div className="mt-6 flex justify-end gap-2"><button onClick={()=>setOperation(null)} className="secondary">Abbrechen</button><button onClick={executeOperation} className="danger">Aktion bestätigen</button></div></Modal>}
    {confirmEvent && <Modal close={()=>setConfirmEvent(null)}><Shield className="h-8 w-8 text-red-300"/><h3 className="mt-4 text-xl font-black text-white">Quelle wirklich sperren?</h3><p className="mt-2 text-sm leading-6 text-slate-400">IP <code>{confirmEvent.ip}</code> wird dauerhaft gesperrt. Interne Netze werden serverseitig abgelehnt. Die Regel kann jederzeit im Bereich „Sperren & Entsperren“ aufgehoben werden.</p><div className="mt-6 flex justify-end gap-2"><button onClick={()=>setConfirmEvent(null)} className="secondary">Abbrechen</button><button onClick={stopAttack} className="danger">Manuell sperren</button></div></Modal>}
    {report && <Modal close={()=>setReport(null)}><BrainCircuit className="h-8 w-8 text-violet-300"/><h3 className="mt-4 text-xl font-black text-white">Grok-Bericht</h3><p className="mt-1 text-xs text-amber-300">Nur Beratung. Keine Regel oder Aktion wurde durch KI ausgeführt.</p><pre className="mt-5 whitespace-pre-wrap rounded-xl border border-slate-800 bg-black/20 p-4 font-sans text-sm leading-6 text-slate-300">{report.report}</pre></Modal>}

    <style jsx global>{`.input{width:100%;border:1px solid rgb(51 65 85);background:#09090c;border-radius:.75rem;padding:.72rem .8rem;color:white;font-size:.875rem;outline:none}.input:focus{border-color:rgba(34,211,238,.55)}.primary,.secondary,.danger{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;border-radius:.75rem;padding:.72rem 1rem;font-size:.8rem;font-weight:800}.primary{background:rgb(34 211 238);color:#071014}.secondary{border:1px solid rgb(51 65 85);color:rgb(203 213 225)}.danger{background:rgb(239 68 68);color:white}`}</style>
  </div>;
}

function Panel({title,icon:Icon,children}:{title:string;icon:any;children:React.ReactNode}) { return <section className="rounded-2xl border border-slate-800 bg-[#131318] p-5"><div className="mb-5 flex items-center gap-2"><Icon className="h-5 w-5 text-cyan-300"/><h3 className="font-black text-white">{title}</h3></div>{children}</section>; }
function Metric({icon:Icon,label,value}:{icon:any;label:string;value:any}) { return <div className="rounded-2xl border border-slate-800 bg-[#131318] p-4"><Icon className="h-4 w-4 text-cyan-300"/><p className="mt-3 text-2xl font-black text-white">{value || 0}</p><p className="text-xs text-slate-500">{label}</p></div>; }
function Status({active,label}:{active:boolean;label:string}) { return <span className={cn("h-fit whitespace-nowrap rounded-full border px-3 py-2 text-[11px] font-black",active?"border-emerald-500/25 bg-emerald-500/10 text-emerald-300":"border-amber-500/25 bg-amber-500/10 text-amber-300")}>{label}</span>; }
function Guarantee({title,text}:{title:string;text:string}) { return <div className="flex gap-3 rounded-xl border border-slate-800 p-3"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-400"/><div><p className="text-sm font-bold text-white">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div></div>; }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="mt-4 block text-xs font-bold text-slate-500">{label}<div className="mt-2">{children}</div></label>; }
function NumberField({label,value,set}:{label:string;value:number;set:(value:number)=>void}) { return <Field label={label}><input className="input" type="number" min="1" value={value} onChange={event=>set(Number(event.target.value))}/></Field>; }
function Toggle({label,text,value,set,danger=false}:{label:string;text:string;value:boolean;set:(value:boolean)=>void;danger?:boolean}) { return <button onClick={()=>set(!value)} className={cn("flex items-center gap-3 rounded-xl border p-4 text-left",value?(danger?"border-amber-500/25 bg-amber-500/[.05]":"border-cyan-500/25 bg-cyan-500/[.05]"):"border-slate-800")}><span className={cn("h-5 w-9 shrink-0 rounded-full p-0.5",value?(danger?"bg-amber-500":"bg-cyan-500"):"bg-slate-700")}><span className={cn("block h-4 w-4 rounded-full bg-white transition",value&&"translate-x-4")}/></span><span><strong className="block text-sm text-white">{label}</strong><small className="text-slate-500">{text}</small></span></button>; }
function RuleRow({rule,remove,edit}:{rule:Rule;remove:(rule:Rule)=>void;edit:(rule:Rule)=>void}) { const allow=rule.kind==="allow"||rule.kind==="user_allow"; return <div className={cn("flex items-center gap-3 rounded-xl border border-slate-800 p-3",!rule.enabled&&"opacity-50")}><span className={cn("rounded-lg px-2 py-1 text-[10px] font-black",allow?"bg-emerald-500/10 text-emerald-300":"bg-red-500/10 text-red-300")}>{ruleNames[rule.kind] || rule.kind}</span><div className="min-w-0 flex-1"><p className="truncate font-mono text-sm text-white">{rule.value}</p><p className="truncate text-xs text-slate-600">{rule.note || "Keine Notiz"} · Priorität {rule.priority || 100} · {rule.enabled?"aktiv":"deaktiviert"} · {rule.expires_at?`bis ${fmt(rule.expires_at)}`:"dauerhaft"}</p></div><button title="Regel bearbeiten" onClick={()=>edit(rule)} className="rounded-lg p-2 text-slate-600 hover:bg-cyan-500/10 hover:text-cyan-300"><Settings2 className="h-4 w-4"/></button><button title="Regel entfernen / entsperren" onClick={()=>remove(rule)} className="rounded-lg p-2 text-slate-600 hover:bg-red-500/10 hover:text-red-300">{allow?<Trash2 className="h-4 w-4"/>:<Undo2 className="h-4 w-4"/>}</button></div>; }
function EventRow({event,onStop,onAnalyze,onAcknowledge,onDetails}:{event:Event;onStop:(event:Event)=>void;onAnalyze:(event:Event)=>void;onAcknowledge:(event:Event)=>void;onDetails?:(event:Event)=>void}) { return <div className="rounded-xl border border-slate-800 bg-black/10 p-3"><div className="flex flex-wrap items-center gap-2"><span className={cn("rounded-md px-2 py-1 text-[10px] font-black",event.blocked?"bg-red-500/10 text-red-300":event.category==="rate_alarm"?"bg-amber-500/10 text-amber-300":"bg-slate-800 text-slate-400")}>{event.blocked?"blockiert":"nur Alarm"}</span><code className="text-xs text-white">{event.ip}</code>{event.actor_id&&<span className="text-[10px] text-cyan-300">User {event.actor_id}</span>}<span className="ml-auto text-[10px] text-slate-600">{fmt(event.created_at)}</span></div><p className="mt-2 break-all text-xs text-slate-400">{event.method} {event.path} · {event.category} · {event.request_count} Anfragen</p><div className="mt-3 flex flex-wrap gap-2">{onDetails&&<button onClick={()=>onDetails(event)} className="secondary !px-3 !py-2 !text-[11px]"><Search className="h-3 w-3"/>Details & Aktionen</button>}<button onClick={()=>onStop(event)} className="danger !px-3 !py-2 !text-[11px]">Quelle sperren</button><button onClick={()=>onAcknowledge(event)} className="secondary !px-3 !py-2 !text-[11px]"><EyeOff className="h-3 w-3"/>Nur schließen</button><button onClick={()=>onAnalyze(event)} className="secondary !px-3 !py-2 !text-[11px]"><BrainCircuit className="h-3 w-3"/>Grok-Bericht</button></div></div>; }
function Empty({text}:{text:string}) { return <div className="rounded-xl border border-dashed border-slate-700 p-8 text-center"><CheckCircle2 className="mx-auto h-6 w-6 text-emerald-400"/><p className="mt-2 text-sm text-slate-500">{text}</p></div>; }
function Result({allowed,title,text}:{allowed:boolean;title:string;text:string}) { return <div className={cn("mt-4 rounded-xl border p-4",allowed?"border-emerald-500/20 bg-emerald-500/[.05]":"border-red-500/20 bg-red-500/[.05]")}><p className={cn("text-sm font-black",allowed?"text-emerald-300":"text-red-300")}>{title}</p><p className="mt-1 text-xs text-slate-400">{text}</p></div>; }
function StatusLine({label,value}:{label:string;value:string}) { return <div className="flex items-center justify-between rounded-xl border border-slate-800 p-3"><span className="text-sm text-slate-400">{label}</span><span className="text-xs font-black text-emerald-300">{value}</span></div>; }
function AuditValue({label,value,color}:{label:string;value:any;color:"red"|"green"}) { return <div className={cn("rounded-lg border p-3",color==="red"?"border-red-500/15 bg-red-500/[.04]":"border-emerald-500/15 bg-emerald-500/[.04]")}><p className={cn("text-[10px] font-black uppercase tracking-wider",color==="red"?"text-red-300":"text-emerald-300")}>{label}</p><pre className="mt-2 max-h-32 overflow-auto whitespace-pre-wrap break-all text-[10px] text-slate-400">{value===null||value===undefined?"—":typeof value==="string"?value:JSON.stringify(value,null,2)}</pre></div>; }
function DiffBox({color,text}:{color:"red"|"green";text:string}) { return <div className={cn("rounded-lg border p-3 font-mono text-xs",color==="red"?"border-red-500/20 bg-red-500/[.05] text-red-200":"border-emerald-500/20 bg-emerald-500/[.05] text-emerald-200")}>{color==="red"?"−":"+"} {text}</div>; }
function DiffPair({before,after}:{before:any;after:any}) { return <div className="mt-2 grid gap-2 sm:grid-cols-2"><AuditValue label="Sicherung" value={before} color="red"/><AuditValue label="Aktuell" value={after} color="green"/></div>; }
function DiffSection({title,items,render}:{title:string;items:any[];render:(item:any)=>React.ReactNode}) { if(!items?.length)return null;return <section><p className="mb-2 text-xs font-black uppercase tracking-wider text-slate-500">{title} · {items.length}</p><div className="space-y-2">{items.map((item,index)=><div key={index}>{render(item)}</div>)}</div></section>; }
function MiniBars({items}:{items:{label:string;value:number;secondary?:number}[]}) { const max=Math.max(1,...items.map(item=>item.value)); return <div className="flex min-h-44 items-end gap-1 overflow-x-auto pt-6">{items.length?items.map((item,index)=><div key={`${item.label}-${index}`} className="group flex min-w-5 flex-1 flex-col items-center justify-end"><div className="relative w-full rounded-t bg-cyan-500/30 transition group-hover:bg-cyan-400/60" style={{height:`${Math.max(4,(item.value/max)*140)}px`}}><span className="absolute -top-5 left-1/2 hidden -translate-x-1/2 whitespace-nowrap text-[9px] text-white group-hover:block">{item.value} · {item.secondary||0} blockiert</span></div><span className="mt-2 text-[8px] text-slate-600">{item.label}</span></div>):<p className="m-auto text-sm text-slate-600">Noch keine Daten</p>}</div>; }
function RankList({items}:{items:{label:string;value:number;meta?:string}[]}) { const max=Math.max(1,...items.map(item=>item.value)); return <div className="space-y-3">{items.length?items.map((item,index)=><div key={`${item.label}-${index}`}><div className="mb-1 flex items-center justify-between gap-3"><span className="truncate text-xs text-slate-300" title={item.label}>{item.label}</span><span className="shrink-0 text-[10px] text-slate-500">{item.value}{item.meta?` · ${item.meta}`:""}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-cyan-400/60" style={{width:`${(item.value/max)*100}%`}}/></div></div>):<p className="text-sm text-slate-600">Noch keine Daten</p>}</div>; }
function Preset({title,text,color,action}:{title:string;text:string;color:string;action:()=>void}) { const colors:Record<string,string>={emerald:"border-emerald-500/25 hover:bg-emerald-500/[.06]",cyan:"border-cyan-500/25 hover:bg-cyan-500/[.06]",amber:"border-amber-500/25 hover:bg-amber-500/[.06]",red:"border-red-500/25 hover:bg-red-500/[.06]"}; return <button onClick={action} className={cn("rounded-2xl border p-4 text-left transition",colors[color])}><p className="font-black text-white">{title}</p><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></button>; }
function Tool({title,text,action,danger=false}:{title:string;text:string;action:()=>void;danger?:boolean}) { return <button onClick={action} className={cn("mb-2 flex w-full items-center gap-3 rounded-xl border p-4 text-left transition",danger?"border-red-500/20 hover:bg-red-500/[.05]":"border-slate-800 hover:border-slate-600")}><span className={cn("grid h-9 w-9 shrink-0 place-items-center rounded-lg",danger?"bg-red-500/10 text-red-300":"bg-cyan-500/10 text-cyan-300")}>{danger?<Trash2 className="h-4 w-4"/>:<Settings2 className="h-4 w-4"/>}</span><span><strong className="block text-sm text-white">{title}</strong><small className="mt-1 block leading-5 text-slate-500">{text}</small></span></button>; }
function CustomSelect({value,onChange,title,options}:{value:string;onChange:(value:string)=>void;title:string;options:{value:string;label:string;description?:string}[]}) {
  const [open,setOpen]=useState(false); const [search,setSearch]=useState("");
  const current=options.find(option=>option.value===value);
  const visible=options.filter(option=>`${option.label} ${option.description||""}`.toLowerCase().includes(search.toLowerCase()));
  useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false)};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close)},[open]);
  return <><button type="button" aria-haspopup="dialog" aria-expanded={open} onClick={()=>{setSearch("");setOpen(true)}} className="input flex items-center justify-between text-left"><span>{current?.label||"Auswählen"}</span><ChevronDown className="h-4 w-4 text-slate-500"/></button>{open&&<div role="dialog" aria-modal="true" className="fixed inset-0 z-[10060] grid place-items-center bg-black/80 p-4 backdrop-blur-sm" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false)}}><div className="w-full max-w-md rounded-3xl border border-cyan-500/20 bg-[#131318] p-5 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Custom-Auswahl</p><h3 className="mt-1 text-lg font-black text-white">{title}</h3></div><button onClick={()=>setOpen(false)} className="rounded-lg p-2 text-slate-500 hover:bg-white/5 hover:text-white"><X className="h-5 w-5"/></button></div>{options.length>5&&<div className="relative mt-4"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-600"/><input autoFocus value={search} onChange={event=>setSearch(event.target.value)} className="input pl-9" placeholder="Option suchen …"/></div>}<div className="mt-4 max-h-[60vh] space-y-2 overflow-y-auto">{visible.map(option=><button key={option.value} onClick={()=>{onChange(option.value);setOpen(false)}} className={cn("w-full rounded-xl border p-4 text-left transition",option.value===value?"border-cyan-500/40 bg-cyan-500/10":"border-slate-800 hover:border-slate-600 hover:bg-white/[.03]")}><span className="flex items-center gap-2 text-sm font-bold text-white">{option.value===value&&<CheckCircle2 className="h-4 w-4 text-cyan-300"/>}{option.label}</span>{option.description&&<span className="mt-1 block text-xs text-slate-500">{option.description}</span>}</button>)}{!visible.length&&<p className="p-6 text-center text-sm text-slate-600">Keine passende Option</p>}</div><p className="mt-3 text-center text-[10px] text-slate-600">ESC oder außerhalb klicken zum Schließen</p></div></div>}</>;
}
function Modal({close,children}:{close:()=>void;children:React.ReactNode}) { return <div className="fixed inset-0 z-[10050] grid place-items-center bg-black/80 p-4 backdrop-blur-sm"><div className="relative max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-3xl border border-slate-700 bg-[#131318] p-6"><button onClick={close} className="absolute right-4 top-4 text-slate-500 hover:text-white"><X className="h-5 w-5"/></button>{children}</div></div>; }
