"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { Activity,AlertTriangle,Ban,BrainCircuit,CheckCircle2,Clock3,Globe2,Loader2,LockKeyhole,Plus,RefreshCw,Save,Search,Shield,ShieldAlert,Trash2,X,Zap } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/api";
import { cn } from "@/lib/utils";

type Tab="overview"|"attacks"|"rules"|"settings";
const when=(v:number)=>new Date(v*1000).toLocaleString("de-DE");
export function FirewallPanel(){const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[tab,setTab]=useState<Tab>("overview"),[busy,setBusy]=useState(false),[rule,setRule]=useState({kind:"block",value:"",note:"",minutes:0}),[report,setReport]=useState<any>(null),[confirmId,setConfirmId]=useState<number|null>(null),[query,setQuery]=useState("");
 const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{setData(await api.getFirewallOverview())}catch(e:any){toast.error(e?.message||"Firewall konnte nicht geladen werden.")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);useEffect(()=>{const id=setInterval(()=>void load(true),10000);return()=>clearInterval(id)},[load]);
 const events=useMemo(()=>((data?.events||[]) as any[]).filter(e=>`${e.ip} ${e.path} ${e.category}`.toLowerCase().includes(query.toLowerCase())),[data,query]);
 const saveSettings=async()=>{setBusy(true);try{await api.updateFirewallSettings(data.settings);toast.success("Firewall-Einstellungen gespeichert.");await load(true)}catch(e:any){toast.error(e?.message||"Speichern fehlgeschlagen.")}finally{setBusy(false)}};
 const addRule=async()=>{setBusy(true);try{await api.addFirewallRule(rule);setRule({...rule,value:"",note:""});toast.success("Firewall-Regel aktiviert.");await load(true)}catch(e:any){toast.error(e?.message||"Regel ungültig.")}finally{setBusy(false)}};
 const stop=async(id:number)=>{setBusy(true);try{await api.stopFirewallIncident(id);setConfirmId(null);toast.success("Angriff gestoppt und IP blockiert.");await load(true)}catch(e:any){toast.error(e?.message||"Angriff konnte nicht gestoppt werden.")}finally{setBusy(false)}};
 const analyze=async(id:number)=>{setBusy(true);try{const result=await api.analyzeFirewallIncident(id);setReport(result);await load(true)}catch(e:any){toast.error(e?.message||"Grok-Bericht nicht verfügbar.")}finally{setBusy(false)}};
 if(loading)return <div className="grid min-h-72 place-items-center"><Loader2 className="h-7 w-7 animate-spin text-cyan-400"/></div>;const s=data?.settings||{};return <div className={cn("space-y-5",busy&&"pointer-events-none opacity-80")}>
 <section className="relative overflow-hidden rounded-3xl border border-cyan-500/20 bg-[#111116] p-6"><div className="absolute inset-0 bg-[radial-gradient(circle_at_90%_0%,rgba(6,182,212,.12),transparent_40%)]"/><div className="relative flex flex-col gap-4 sm:flex-row sm:items-center"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-cyan-500/10"><Shield className="h-7 w-7 text-cyan-300"/></span><div className="flex-1"><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">Application Firewall</p><h2 className="mt-1 text-2xl font-black text-white">Website- und API-Schutz</h2><p className="mt-1 text-sm text-slate-500">Erkennung und Sperren laufen regelbasiert. Grok erstellt ausschließlich Vorschläge und darf niemals selbst handeln.</p></div><span className={cn("w-fit rounded-full border px-3 py-1.5 text-xs font-black",s.enabled?"border-emerald-500/25 bg-emerald-500/10 text-emerald-300":"border-red-500/25 bg-red-500/10 text-red-300")}>{s.enabled?"Schutz aktiv":"Schutz ausgeschaltet"}</span></div></section>
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat icon={Activity} label="Ereignisse · 24h" value={data.stats.events_24h}/><Stat icon={Ban} label="Blockiert · 24h" value={data.stats.blocked_24h}/><Stat icon={ShieldAlert} label="Kritisch · 24h" value={data.stats.critical_24h}/><Stat icon={Globe2} label="Quell-IPs · 24h" value={data.stats.unique_ips_24h}/></div>
 <div className="flex gap-1 overflow-x-auto rounded-xl border border-slate-800 bg-[#131318] p-1">{[["overview","Übersicht",Shield],["attacks","Live-Angriffe",Zap],["rules","Regeln & IPs",Ban],["settings","Einstellungen",LockKeyhole]].map(([id,label,Icon]:any)=><button key={id} onClick={()=>setTab(id)} className={cn("flex shrink-0 items-center gap-2 rounded-lg px-4 py-2.5 text-xs font-bold",tab===id?"bg-cyan-500/10 text-cyan-200":"text-slate-500 hover:text-white")}><Icon className="h-4 w-4"/>{label}</button>)}</div>
 {tab==="overview"&&<div className="grid gap-4 lg:grid-cols-2"><Card title="Aktive Angriffe" icon={AlertTriangle}>{data.active_incidents.length?data.active_incidents.slice(0,8).map((e:any)=><Event key={e.id} e={e} stop={setConfirmId} analyze={analyze}/>):<Empty text="Aktuell wurde kein laufender Angriff erkannt."/>}</Card><Card title="Letzte Schutzereignisse" icon={Clock3}>{events.slice(0,10).map((e:any)=><Event key={e.id} e={e} compact stop={setConfirmId} analyze={analyze}/>)}</Card></div>}
 {tab==="attacks"&&<Card title="Angriffe und Ereignisse der letzten 90 Tage" icon={Zap}><div className="mb-4 flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-600"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="IP, Pfad oder Kategorie suchen …" className="w-full rounded-xl border border-slate-700 bg-[#09090c] py-2.5 pl-9 pr-3 text-sm text-white"/></div><button onClick={()=>load()} className="rounded-xl border border-slate-700 px-3"><RefreshCw className="h-4 w-4 text-slate-400"/></button></div><div className="space-y-2">{events.map((e:any)=><Event key={e.id} e={e} stop={setConfirmId} analyze={analyze}/>)}</div></Card>}
 {tab==="rules"&&<div className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><Card title="Neue Regel" icon={Plus}><label className="text-xs font-bold text-slate-500">Regelart</label><select value={rule.kind} onChange={e=>setRule({...rule,kind:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-700 bg-[#09090c] p-3 text-sm text-white"><option value="block">IP/CIDR blockieren</option><option value="allow">IP/CIDR erlauben</option><option value="user_agent">User-Agent blockieren</option><option value="path">Pfad-Muster blockieren</option></select><label className="mt-4 block text-xs font-bold text-slate-500">Wert</label><input value={rule.value} onChange={e=>setRule({...rule,value:e.target.value})} placeholder={rule.kind==="block"||rule.kind==="allow"?"203.0.113.4 oder 203.0.113.0/24":"Muster eingeben"} className="mt-2 w-full rounded-xl border border-slate-700 bg-[#09090c] p-3 text-sm text-white"/><label className="mt-4 block text-xs font-bold text-slate-500">Dauer in Minuten · 0 = dauerhaft</label><input type="number" min="0" value={rule.minutes} onChange={e=>setRule({...rule,minutes:Number(e.target.value)})} className="mt-2 w-full rounded-xl border border-slate-700 bg-[#09090c] p-3 text-sm text-white"/><input value={rule.note} onChange={e=>setRule({...rule,note:e.target.value})} placeholder="Interne Notiz" className="mt-3 w-full rounded-xl border border-slate-700 bg-[#09090c] p-3 text-sm text-white"/><button onClick={addRule} className="mt-4 w-full rounded-xl bg-cyan-500 py-3 text-sm font-black text-black">Regel aktivieren</button></Card><Card title="Aktive Regeln" icon={Ban}><div className="space-y-2">{data.rules.map((r:any)=><div key={r.id} className="flex items-center gap-3 rounded-xl border border-slate-800 p-3"><span className={cn("rounded-lg px-2 py-1 text-[10px] font-black",r.kind==="allow"?"bg-emerald-500/10 text-emerald-300":"bg-red-500/10 text-red-300")}>{r.kind}</span><div className="min-w-0 flex-1"><p className="truncate font-mono text-sm text-white">{r.value}</p><p className="truncate text-xs text-slate-600">{r.note||"Keine Notiz"}{r.expires_at?` · bis ${when(r.expires_at)}`:" · dauerhaft"}</p></div><button onClick={async()=>{await api.deleteFirewallRule(r.id);await load(true)}} className="text-slate-600 hover:text-red-300"><Trash2 className="h-4 w-4"/></button></div>)}</div></Card></div>}
 {tab==="settings"&&<Card title="Firewall-Einstellungen" icon={LockKeyhole}><div className="grid gap-3 md:grid-cols-2"><Toggle label="Firewall aktiv" text="Gesamten Website- und API-Schutz schalten" value={s.enabled} set={v=>setData({...data,settings:{...s,enabled:v}})}/><Toggle label="Notfallmodus" text="Deutlich schärferes globales Rate-Limit" value={s.emergency_mode} set={v=>setData({...data,settings:{...s,emergency_mode:v}})}/><Toggle label="Scanner blockieren" text="Bekannte Scanner wie sqlmap, Nikto und Masscan" value={s.block_bad_bots} set={v=>setData({...data,settings:{...s,block_bad_bots:v}})}/></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><NumberField label="Anfragen pro Minute" value={s.requests_per_minute} set={v=>setData({...data,settings:{...s,requests_per_minute:v}})}/><NumberField label="Burst in 10 Sekunden" value={s.burst_10_seconds} set={v=>setData({...data,settings:{...s,burst_10_seconds:v}})}/><NumberField label="Automatische Sperre · Minuten" value={s.auto_block_minutes} set={v=>setData({...data,settings:{...s,auto_block_minutes:v}})}/><NumberField label="Notfall-Limit pro Minute" value={s.emergency_rpm} set={v=>setData({...data,settings:{...s,emergency_rpm:v}})}/></div><label className="mt-5 block text-xs font-bold text-slate-500">Länder-Blockliste · ISO-Codes, komma-getrennt</label><input value={(s.country_blocklist||[]).join(",")} onChange={e=>setData({...data,settings:{...s,country_blocklist:e.target.value.split(",")}})} placeholder="RU,CN" className="mt-2 w-full rounded-xl border border-slate-700 bg-[#09090c] p-3 text-sm text-white"/><div className="mt-5 flex justify-between rounded-xl border border-blue-500/20 bg-blue-500/[.05] p-4 text-xs text-blue-200"><span>IP-Ereignisse werden 90 Tage gespeichert. Grok darf ausschließlich Berichte und Vorschläge erstellen.</span></div><button onClick={saveSettings} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-5 py-3 text-sm font-black text-black"><Save className="h-4 w-4"/>Einstellungen speichern</button></Card>}
 {confirmId!==null&&<div className="fixed inset-0 z-[10040] grid place-items-center bg-black/80 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-3xl border border-red-500/25 bg-[#131318] p-6"><ShieldAlert className="h-8 w-8 text-red-300"/><h3 className="mt-4 text-xl font-black text-white">Angriff manuell stoppen?</h3><p className="mt-2 text-sm leading-6 text-slate-400">Die Quell-IP wird dauerhaft blockiert und der Vorfall als gestoppt markiert. Die Sperre kann danach im Bereich „Regeln & IPs“ jederzeit rückgängig gemacht werden.</p><div className="mt-6 flex justify-end gap-2"><button onClick={()=>setConfirmId(null)} className="rounded-xl border border-slate-700 px-4 py-2.5 text-sm font-bold text-slate-400">Abbrechen</button><button onClick={()=>stop(confirmId)} className="rounded-xl bg-red-500 px-4 py-2.5 text-sm font-black text-white">Jetzt stoppen</button></div></div></div>}
 {report&&<div className="fixed inset-0 z-[10040] grid place-items-center bg-black/80 p-4 backdrop-blur-sm"><div className="relative max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-3xl border border-violet-500/25 bg-[#131318] p-6"><button onClick={()=>setReport(null)} className="absolute right-4 top-4 text-slate-500"><X className="h-5 w-5"/></button><BrainCircuit className="h-7 w-7 text-violet-300"/><h3 className="mt-3 text-xl font-black text-white">Grok-Sicherheitsbericht</h3><p className="mt-1 text-xs text-amber-300">Nur Empfehlung – keine Aktion wurde durch die KI ausgeführt.</p><pre className="mt-5 whitespace-pre-wrap rounded-xl border border-slate-800 bg-black/20 p-4 font-sans text-sm leading-6 text-slate-300">{report.report}</pre></div></div>}
 </div>}
function Card({title,icon:Icon,children}:{title:string,icon:any,children:React.ReactNode}){return <section className="rounded-2xl border border-slate-800 bg-[#131318] p-5"><div className="mb-4 flex items-center gap-2"><Icon className="h-5 w-5 text-cyan-300"/><h3 className="font-black text-white">{title}</h3></div>{children}</section>}
function Stat({icon:Icon,label,value}:{icon:any,label:string,value:any}){return <div className="rounded-2xl border border-slate-800 bg-[#131318] p-4"><Icon className="h-4 w-4 text-cyan-300"/><p className="mt-3 text-2xl font-black text-white">{value||0}</p><p className="text-xs text-slate-500">{label}</p></div>}
function Event({e,stop,analyze,compact=false}:{e:any,stop:(id:number)=>void,analyze:(id:number)=>void,compact?:boolean}){return <div className="rounded-xl border border-slate-800 bg-black/10 p-3"><div className="flex flex-wrap items-center gap-2"><span className={cn("rounded-md px-2 py-1 text-[10px] font-black",e.severity==="critical"?"bg-red-500/10 text-red-300":e.severity==="high"?"bg-amber-500/10 text-amber-300":"bg-slate-800 text-slate-400")}>{e.severity}</span><code className="text-xs text-white">{e.ip}</code><span className="ml-auto text-[10px] text-slate-600">{when(e.created_at)}</span></div><p className="mt-2 truncate text-xs text-slate-400">{e.method} {e.path} · {e.category} · {e.request_count} Anfragen</p>{!compact&&<div className="mt-3 flex gap-2"><button onClick={()=>stop(e.id)} className="rounded-lg bg-red-500 px-3 py-2 text-[11px] font-black text-white">Angriff stoppen</button><button onClick={()=>analyze(e.id)} className="rounded-lg border border-violet-500/25 px-3 py-2 text-[11px] font-bold text-violet-300"><BrainCircuit className="mr-1 inline h-3 w-3"/>Grok-Bericht</button></div>}{e.ai_report&&<p className="mt-2 truncate text-[10px] text-violet-300">KI-Bericht vorhanden</p>}</div>}
function Toggle({label,text,value,set}:{label:string,text:string,value:boolean,set:(v:boolean)=>void}){return <button onClick={()=>set(!value)} className={cn("flex items-center gap-3 rounded-xl border p-4 text-left",value?"border-cyan-500/25 bg-cyan-500/[.06]":"border-slate-800")}><span className={cn("h-5 w-9 rounded-full p-0.5",value?"bg-cyan-500":"bg-slate-700")}><span className={cn("block h-4 w-4 rounded-full bg-white transition",value&&"translate-x-4")}/></span><span><strong className="block text-sm text-white">{label}</strong><small className="text-slate-500">{text}</small></span></button>}
function NumberField({label,value,set}:{label:string,value:number,set:(v:number)=>void}){return <label className="text-xs font-bold text-slate-500">{label}<input type="number" min="1" value={value} onChange={e=>set(Number(e.target.value))} className="mt-2 w-full rounded-xl border border-slate-700 bg-[#09090c] p-3 text-sm text-white"/></label>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-slate-700 p-8 text-center"><CheckCircle2 className="mx-auto h-6 w-6 text-emerald-400"/><p className="mt-2 text-sm text-slate-500">{text}</p></div>}
