"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, Crown, Infinity as InfinityIcon, Loader2, Search, Server, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/api";
import { cn } from "@/lib/utils";

export function PremiumServerAdmin() {
  const [guilds,setGuilds]=useState<any[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState("");
  const [grant,setGrant]=useState<any>(null),[revoke,setRevoke]=useState<any>(null),[days,setDays]=useState("30"),[lifetime,setLifetime]=useState(false),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{const data=await api.getAdminPremiumServers();setGuilds(data.guilds||[])}catch(e:any){toast.error(e?.message||"Server konnten nicht geladen werden.")}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const shown=useMemo(()=>guilds.filter(g=>`${g.name} ${g.guild_id}`.toLowerCase().includes(search.toLowerCase().trim())),[guilds,search]);
  const submitGrant=async()=>{const value=Number(days);if(!lifetime&&(!Number.isInteger(value)||value<1))return toast.error("Gib mindestens einen Tag ein.");setBusy(true);try{await api.grantAdminPremiumServer(grant.guild_id,value,lifetime);toast.success("Server-Premium wurde vergeben. Der Serverinhaber erhält ein Popup.");setGrant(null);await load()}catch(e:any){toast.error(e?.message||"Premium konnte nicht vergeben werden.")}finally{setBusy(false)}};
  const submitRevoke=async(deleteSettings:boolean)=>{setBusy(true);try{await api.revokeAdminPremiumServer(revoke.guild_id,deleteSettings);toast.success(deleteSettings?"Premium und alle Premium-Einstellungen wurden entfernt.":"Premium wurde entzogen; Einstellungen bleiben erhalten.");setRevoke(null);await load()}catch(e:any){toast.error(e?.message||"Premium konnte nicht entzogen werden.")}finally{setBusy(false)}};
  return <div className="space-y-4"><div className="flex flex-col gap-3 rounded-2xl border border-slate-800 bg-[#131318] p-5 sm:flex-row sm:items-center"><div className="flex-1"><h3 className="font-black text-white">Premiumserver verwalten</h3><p className="mt-1 text-xs text-slate-500">Direkte Admin-Freigaben verbrauchen keinen Konto-Platz. Der tatsächliche Serverinhaber wird per Dashboard-Popup informiert.</p></div><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-600"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Server suchen …" className="rounded-xl border border-slate-700 bg-[#09090c] py-2.5 pl-9 pr-3 text-sm text-white"/></div></div>{loading?<div className="grid min-h-48 place-items-center"><Loader2 className="animate-spin text-amber-300"/></div>:<div className="grid gap-3 lg:grid-cols-2">{shown.map(g=>{const active=g.state?.active;const direct=g.state?.direct_admin_grant;return <article key={g.guild_id} className="rounded-2xl border border-slate-800 bg-[#131318] p-4"><div className="flex gap-3">{g.icon?<img src={g.icon} alt="" className="h-11 w-11 rounded-xl"/>:<span className="grid h-11 w-11 place-items-center rounded-xl bg-slate-800"><Server className="h-5 w-5 text-slate-500"/></span>}<div className="min-w-0 flex-1"><p className="truncate font-black text-white">{g.name}</p><p className="text-xs text-slate-600">{g.guild_id} · {g.members.toLocaleString("de-DE")} Mitglieder</p></div><span className={cn("h-fit rounded-full px-2.5 py-1 text-[10px] font-black",active?"bg-emerald-500/10 text-emerald-300":"bg-slate-800 text-slate-500")}>{active?direct?"Admin-Premium":"Konto-Premium":"Free"}</span></div><div className="mt-4 flex items-center justify-between border-t border-slate-800 pt-3"><div className="text-xs text-slate-500">{active?<><Clock3 className="mr-1 inline h-3.5 w-3.5"/>{g.state.duration_days===0?"Dauerhaft":`bis ${new Date(g.state.expires_at*1000).toLocaleDateString("de-DE")}`}</>:"Keine aktive Freigabe"}</div>{active?<button onClick={()=>setRevoke(g)} className="rounded-lg border border-red-500/25 px-3 py-2 text-xs font-bold text-red-300">Entziehen</button>:<button onClick={()=>{setGrant(g);setDays("30");setLifetime(false)}} className="rounded-lg bg-amber-400 px-3 py-2 text-xs font-black text-black">Premium geben</button>}</div></article>})}</div>}
  {grant&&<Modal close={()=>setGrant(null)}><Crown className="h-7 w-7 text-amber-300"/><h3 className="mt-4 text-xl font-black text-white">{grant.name} Premium geben</h3><p className="mt-2 text-sm text-slate-400">Der Serverinhaber <strong className="text-white">{grant.owner_user_id}</strong> erhält danach ein eigenes Dashboard-Popup.</p><label className="mt-5 block text-xs font-bold text-slate-500">Beliebige Laufzeit in Tagen</label><input disabled={lifetime} value={days} onChange={e=>setDays(e.target.value)} type="number" min="1" className="mt-2 w-full rounded-xl border border-slate-700 bg-[#09090c] px-4 py-3 text-white disabled:opacity-40"/><button onClick={()=>setLifetime(v=>!v)} className={cn("mt-3 flex w-full items-center gap-3 rounded-xl border p-3 text-left",lifetime?"border-amber-400/30 bg-amber-400/10":"border-slate-700")}><InfinityIcon className="h-5 w-5 text-amber-300"/><span className="text-sm font-bold text-white">Dauerhaftes Premium</span>{lifetime&&<CheckCircle2 className="ml-auto h-5 w-5 text-emerald-400"/>}</button><div className="mt-5 grid grid-cols-2 gap-2"><button onClick={()=>setGrant(null)} className="rounded-xl border border-slate-700 py-3 text-sm font-bold text-slate-300">Abbrechen</button><button disabled={busy} onClick={submitGrant} className="rounded-xl bg-amber-400 py-3 text-sm font-black text-black">Vergeben</button></div></Modal>}
  {revoke&&<Modal close={()=>setRevoke(null)}><AlertTriangle className="h-7 w-7 text-red-300"/><h3 className="mt-4 text-xl font-black text-white">Premium von {revoke.name} entziehen?</h3><p className="mt-2 text-sm leading-6 text-slate-400">Wähle ausdrücklich, was mit den vorhandenen Premium-Einstellungen passieren soll.</p><button disabled={busy} onClick={()=>submitRevoke(false)} className="mt-5 w-full rounded-xl border border-blue-500/25 bg-blue-500/[0.06] p-4 text-left"><p className="font-black text-blue-200">Premium entziehen, Einstellungen behalten</p><p className="mt-1 text-xs leading-5 text-slate-400">Premium wird deaktiviert. Alle Konfigurationen und Inhalte bleiben in der Datenbank.</p></button><button disabled={busy} onClick={()=>submitRevoke(true)} className="mt-3 w-full rounded-xl border border-red-500/30 bg-red-500/[0.06] p-4 text-left"><p className="flex items-center gap-2 font-black text-red-300"><Trash2 className="h-4 w-4"/>Premium-Einstellungen endgültig löschen</p><p className="mt-1 text-xs leading-5 text-slate-400">Löscht Design, Backups, Server-Stats, Premium-Custom-Commands, Ticket-KI-Daten, Pull-Daten und Speedrun-Daten dieses Servers aus den Datenbanken.</p></button><button onClick={()=>setRevoke(null)} className="mt-3 w-full rounded-xl border border-slate-700 py-3 text-sm font-bold text-slate-300">Abbrechen</button></Modal>}
  </div>;
}
function Modal({children,close}:{children:React.ReactNode,close:()=>void}){return <div className="fixed inset-0 z-[10030] grid place-items-center overflow-y-auto bg-black/80 p-4 backdrop-blur-sm"><div className="relative w-full max-w-md rounded-3xl border border-slate-700 bg-[#131318] p-6 shadow-2xl"><button onClick={close} className="absolute right-4 top-4 text-slate-500 hover:text-white"><X className="h-5 w-5"/></button>{children}</div></div>}
