"use client";

import { useCallback, useEffect, useId, useRef, useState } from "react";
import { useSession } from "next-auth/react";
import { AlertTriangle, CheckCircle2, Clock3, Crown, Loader2, Plus, RefreshCw, Search, Server, ShoppingCart, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/api";
import { useWebsiteLocale } from "@/lib/i18n/locale";
import { cn } from "@/lib/utils";

type Guild = { id: string; name: string; icon?: string | null };
type Slot = { slot_no: number; guild_id: string | number; guild_name?: string; guild_icon?: string | null; bot_present?: boolean; premium_active?: boolean; assigned_at: number };
type Premium = { premium: boolean; lifetime: boolean; expires_at?: number; slots: Slot[]; slot_cooldowns: { slot_no: number; available_at: number }[]; server_time: number; purchase_requests: { duration_days: number; status: string }[] };
const plans = [{ days: 30, amount: 2.99 }, { days: 365, amount: 12.99 }, { days: 0, amount: 29.99 }];
const action = "inline-flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-bold transition disabled:cursor-not-allowed disabled:opacity-40";
const card = "rounded-3xl border border-slate-800 cloudtix-workspace-card bg-[#131318] p-5 sm:p-6";

function Avatar({ src, name, large = false }: { src?: string | null; name: string; large?: boolean }) {
  const [failed, setFailed] = useState(false);
  useEffect(() => setFailed(false), [src]);
  const size = large ? "h-16 w-16 rounded-2xl" : "h-11 w-11 rounded-xl";
  return src && !failed ? <img src={src} alt="" onError={() => setFailed(true)} className={cn("shrink-0 object-cover", size)} /> : <span aria-hidden="true" className={cn("grid shrink-0 place-items-center bg-white/5 font-black text-neutral-200", size)}>{name.slice(0, 2).toUpperCase() || <Server className="h-5 w-5" />}</span>;
}

function Modal({ title, closeLabel, busy, close, children, danger = false }: { title: string; closeLabel: string; busy: boolean; close: () => void; children: React.ReactNode; danger?: boolean }) {
  const ref = useRef<HTMLDialogElement>(null);
  const titleId = useId();
  useEffect(() => { const dialog = ref.current; dialog?.showModal(); return () => dialog?.close(); }, []);
  return <dialog ref={ref} data-no-translate aria-labelledby={titleId} onCancel={event => { event.preventDefault(); if (!busy) close(); }} onClick={event => { const box = event.currentTarget.getBoundingClientRect(); if (!busy && (event.clientX < box.left || event.clientX > box.right || event.clientY < box.top || event.clientY > box.bottom)) close(); }} className={cn("w-[calc(100%_-_2rem)] max-w-lg rounded-3xl border cloudtix-workspace-card bg-[#131318] p-6 text-white shadow-2xl backdrop:bg-black/80 backdrop:backdrop-blur-sm", danger ? "border-red-400/30" : "border-white/20")}><div className="mb-4 flex items-center justify-between gap-4"><h3 id={titleId} className="text-xl font-black">{title}</h3><button disabled={busy} aria-label={closeLabel} onClick={close} className="rounded-lg p-2 text-slate-400 hover:text-white"><X className="h-5 w-5" /></button></div>{children}</dialog>;
}

export function PremiumPanel() {
  const locale = useWebsiteLocale();
  const t = (de: string, en: string) => locale === "en-GB" ? en : de;
  const { data: session } = useSession();
  const userId = session?.user?.id;
  const [status, setStatus] = useState<Premium | null>(null);
  const [servers, setServers] = useState<Guild[]>([]);
  const [plan, setPlan] = useState(30);
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  const [assignOpen, setAssignOpen] = useState(false);
  const [selected, setSelected] = useState("");
  const [search, setSearch] = useState("");
  const [release, setRelease] = useState<Slot | null>(null);
  const [clock, setClock] = useState(Date.now());
  const [offset, setOffset] = useState(0);
  const date = (value?: number) => value ? new Date(value * 1000).toLocaleString(locale, { dateStyle: "medium", timeStyle: "short" }) : "–";
  const load = useCallback(async () => {
    if (!userId) return;
    try {
      const [mine, choices] = await Promise.all([api.getMyPremium(userId), api.premiumCodeServers().catch(() => null)]);
      setStatus(mine.premium); setServers(choices?.servers || []); setClock(Date.now());
      setOffset(mine.premium.server_time * 1000 - Date.now());
      if (!choices) toast.warning(locale === "en-GB" ? "Could not load the server list. You can still remove assigned servers. Refresh to try again." : "Die Serverliste konnte nicht geladen werden. Zugewiesene Server kannst du weiterhin entfernen. Versuche es mit Aktualisieren erneut.");
    } catch (error: any) { toast.error(error?.message || (locale === "en-GB" ? "Could not load Premium." : "Premium konnte nicht geladen werden.")); }
    finally { setLoading(false); }
  }, [userId, locale]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const timer = setInterval(() => setClock(Date.now()), 30_000); return () => clearInterval(timer); }, []);
  const now = (clock + offset) / 1000;
  const used = status?.slots || [];
  const cooldowns = (status?.slot_cooldowns || []).filter(item => item.available_at > now);
  const availableSlots = 3 - used.length - cooldowns.length;
  const availableServers = servers.filter(server => !used.some(slot => String(slot.guild_id) === server.id));
  const shownServers = availableServers.filter(server => server.name.toLocaleLowerCase(locale).includes(search.toLocaleLowerCase(locale)));
  const pending = status?.purchase_requests.find(item => item.status === "pending");
  const planLabel = (days: number) => days === 0 ? "Lifetime" : days === 365 ? t("1 Jahr", "1 year") : `${days} ${t("Tage", "days")}`;
  const slotName = (slot: Slot) => slot.guild_name || servers.find(server => server.id === String(slot.guild_id))?.name || t("Server nicht mehr verfügbar", "Server no longer available");
  const perform = async (operation: () => Promise<void>) => { setBusy(true); try { await operation(); await load(); } catch (error: any) { toast.error(error?.message || t("Die Aktion ist fehlgeschlagen.", "The action failed.")); } finally { setBusy(false); } };
  const requestPurchase = () => perform(async () => { const result = await api.requestPremiumPurchase(plan); toast.success(result.already ? t("Deine Kaufanfrage wartet bereits auf Bearbeitung.", "Your purchase request is already pending.") : t("Kaufanfrage an das Team gesendet.", "Purchase request sent to the team.")); });
  const assign = () => perform(async () => { await api.assignPremiumSlot(selected); setAssignOpen(false); setSelected(""); setSearch(""); toast.success(t("Premium wurde dem Server zugewiesen.", "Premium assigned to the server.")); });
  const releaseSlot = () => perform(async () => { if (!release) return; await api.releasePremiumSlot(release.slot_no); setRelease(null); toast.success(t("Server entfernt. Der Platz ist in 30 Tagen wieder frei.", "Server removed. The slot becomes available in 30 days.")); });

  if (loading) return <div className="grid min-h-60 place-items-center"><Loader2 aria-label={t("Laden", "Loading")} className="h-7 w-7 animate-spin text-neutral-300" /></div>;
  if (!status) return <div data-no-translate className={cn(card, "text-center")}><p className="text-slate-400">{t("Premium konnte nicht geladen werden.", "Could not load Premium.")}</p><button onClick={() => void load()} className={cn(action, "mt-4 bg-white text-black")}>{t("Erneut versuchen", "Try again")}</button></div>;
  return <div data-no-translate className="space-y-6">
    <section className="rounded-3xl border border-white/15 cloudtix-workspace-card bg-[#111111] p-5 sm:p-7">
      <div className="flex flex-wrap items-center gap-4"><Avatar src={session?.user?.image} name={session?.user?.name || "Discord"} large /><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-widest text-neutral-400">{t("Dein Premium-Konto", "Your Premium account")}</p><h2 className="mt-1 truncate text-2xl font-black text-white">{session?.user?.name || t("Dein Discord-Konto", "Your Discord account")}</h2><p className="mt-1 text-sm text-slate-400">{t("Deine Mitgliedschaft. Deine Server. Alles an einem Ort.", "Your membership. Your servers. Everything in one place.")}</p></div><button disabled={busy} onClick={() => void load()} aria-label={t("Aktualisieren", "Refresh")} className="rounded-xl border border-white/10 p-3 text-slate-400 hover:text-white"><RefreshCw className="h-4 w-4" /></button></div>
      <div className="mt-6 grid gap-3 sm:grid-cols-3">{[[t("Mitgliedschaft", "Membership"), status.premium ? t("Premium aktiv", "Premium active") : t("Kein aktives Premium", "No active Premium")], [t("Laufzeit", "Access period"), status.lifetime ? t("Lebenslang", "Lifetime") : date(status.expires_at)], [t("Serverplätze", "Server slots"), `${used.length} / 3 ${t("belegt", "assigned")}`]].map(([label, value]) => <div key={label} className="rounded-2xl border border-white/5 bg-black/20 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 font-bold text-white">{value}</p></div>)}</div>
    </section>
    <section className={card}><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="flex items-center gap-2 text-lg font-black text-white"><Crown className="h-5 w-5 text-neutral-300" />{t("Deine Premium-Server", "Your Premium servers")}</h3><p className="mt-2 max-w-xl text-sm text-slate-400">{t("Entferne einen Server jederzeit. Genau dieser Platz bekommt anschließend 30 Tage Cooldown.", "Remove a server at any time. That specific slot then has a 30-day cooldown.")}</p></div><span className="rounded-full bg-white/5 px-3 py-1.5 text-xs font-bold text-neutral-200">{availableSlots} {t("frei", "available")} · {cooldowns.length} {t("im Cooldown", "on cooldown")}</span></div>
      <div className="mt-5 grid gap-3 lg:grid-cols-3">{[1, 2, 3].map(number => { const slot = used.find(item => item.slot_no === number); const cooldown = cooldowns.find(item => item.slot_no === number); return <article key={number} className={cn("flex min-h-56 flex-col rounded-2xl border p-4", slot ? "border-white/15 bg-white/[0.04]" : cooldown ? "border-amber-400/20 bg-amber-400/[0.04]" : "border-dashed border-slate-700")}><p className="text-xs font-bold text-slate-500">{t("Platz", "Slot")} {number}</p>{slot ? <><div className="mt-4 flex items-center gap-3"><Avatar src={slot.guild_icon} name={slotName(slot)} /><h4 className="min-w-0 break-words font-bold text-white">{slotName(slot)}</h4></div><p className={cn("mt-4 flex items-center gap-2 text-xs", slot.bot_present === false ? "text-amber-300" : "text-emerald-300")}><CheckCircle2 className="h-4 w-4 shrink-0" />{slot.bot_present === false ? t("Bot nicht mehr auf diesem Server", "Bot no longer on this server") : slot.premium_active ? t("Premium aktiv", "Premium active") : t("Zuweisung gespeichert", "Assignment saved")}</p><p className="mt-2 text-xs text-slate-500">{t("Zugewiesen am", "Assigned on")} {date(slot.assigned_at)}</p><button disabled={busy} onClick={() => setRelease(slot)} className={cn(action, "mt-5 w-full border border-red-400/20 text-red-300 hover:bg-red-400/10")}><Trash2 className="h-4 w-4" />{t("Server entfernen", "Remove server")}</button></> : cooldown ? <><Clock3 className="mt-4 h-8 w-8 text-amber-300" /><h4 className="mt-3 font-bold text-white">{t("Platz im Cooldown", "Slot on cooldown")}</h4><p className="mt-2 text-sm text-amber-200">{Math.max(1, Math.ceil((cooldown.available_at - now) / 86400))} {t("Tage verbleibend", "days remaining")}</p><p className="mt-2 text-xs leading-5 text-slate-500">{t("Wieder verfügbar am", "Available again on")} {date(cooldown.available_at)}</p></> : <><Plus className="mt-4 h-8 w-8 text-slate-600" /><h4 className="mt-3 font-bold text-white">{t("Freier Serverplatz", "Available server slot")}</h4><p className="mt-2 text-sm text-slate-500">{status.premium ? t("Bereit für deinen nächsten Server.", "Ready for your next server.") : t("Aktiviere Premium, um einen Server hinzuzufügen.", "Activate Premium to add a server.")}</p></>}</article>; })}</div>
      <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="max-w-xl text-xs leading-5 text-slate-500">{t("Beim Entfernen endet das Premium aus diesem Platz sofort. Gespeicherte Einstellungen bleiben erhalten. Andere Plätze werden nicht gesperrt.", "Removing a server ends Premium from this slot immediately. Saved settings remain. Other slots stay available.")}</p><button disabled={busy || !status.premium || availableSlots < 1} onClick={() => setAssignOpen(true)} className={cn(action, "bg-white text-black hover:bg-neutral-200")}><Plus className="h-4 w-4" />{t("Server hinzufügen", "Add server")}</button></div>
    </section>
    {!status.premium && <section className={card}><h3 className="flex items-center gap-2 text-lg font-black text-white"><ShoppingCart className="h-5 w-5 text-neutral-300" />{t("Premium anfragen", "Request Premium")}</h3><p className="mt-2 text-sm text-slate-400">{t("Das Team prüft deinen Kauf im Admin-Panel. Nach der Freigabe erhältst du eine Discord-DM und drei Serverplätze.", "The team reviews your purchase in the admin panel. After approval, you receive a Discord DM and three server slots.")}</p>{pending ? <div role="status" className="mt-5 flex gap-3 rounded-2xl border border-amber-400/20 bg-amber-400/5 p-4"><Clock3 className="h-5 w-5 shrink-0 text-amber-300" /><div><p className="font-bold text-amber-200">{t("Deine Anfrage wird geprüft", "Your request is under review")}</p><p className="mt-1 text-sm text-slate-400">{planLabel(pending.duration_days)} · {t("Du brauchst keine weitere Anfrage zu senden.", "You do not need to send another request.")}</p></div></div> : <><div className="mt-5 grid gap-3 sm:grid-cols-3">{plans.map(item => <button key={item.days} aria-pressed={plan === item.days} onClick={() => setPlan(item.days)} className={cn("cloudtix-workspace-option rounded-2xl border p-4 text-left", plan === item.days ? "border-white/40 bg-white/[0.06]" : "border-slate-800 hover:border-slate-600")}><p className="font-bold text-white">{planLabel(item.days)}</p><p className="mt-3 text-2xl font-black text-white">{new Intl.NumberFormat(locale, { style: "currency", currency: "EUR" }).format(item.amount)}</p><p className="mt-2 text-xs text-slate-500">{t("3 Serverplätze · keine automatische Verlängerung", "3 server slots · no automatic renewal")}</p></button>)}</div><button disabled={busy} onClick={() => void requestPurchase()} className={cn(action, "mt-5 w-full bg-white text-black hover:bg-neutral-200")}>{busy && <Loader2 className="h-4 w-4 animate-spin" />}{t("Kaufanfrage senden", "Send purchase request")}</button></>}</section>}
    {assignOpen && <Modal title={t("Premium-Server hinzufügen", "Add a Premium server")} closeLabel={t("Schließen", "Close")} busy={busy} close={() => setAssignOpen(false)}><p className="text-sm text-slate-400">{t("Wähle einen Server, den du verwaltest und auf dem der Bot installiert ist.", "Choose a server you manage with the bot installed.")}</p><label className="relative mt-4 block"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-500" /><input aria-label={t("Server suchen", "Search servers")} placeholder={t("Server suchen …", "Search servers…")} value={search} onChange={e => setSearch(e.target.value)} className="w-full rounded-xl border border-slate-700 bg-black/20 py-2.5 pl-10 pr-3 text-sm" /></label><div className="mt-3 max-h-64 space-y-2 overflow-y-auto">{shownServers.map(server => <button key={server.id} onClick={() => setSelected(server.id)} aria-pressed={selected === server.id} className={cn("flex w-full items-center gap-3 rounded-xl border p-3 text-left", selected === server.id ? "border-white/40 bg-white/5" : "border-slate-800")}><Avatar src={server.icon} name={server.name} /><span className="min-w-0 flex-1 break-words font-bold">{server.name}</span>{selected === server.id && <CheckCircle2 className="h-5 w-5 text-neutral-300" />}</button>)}{!shownServers.length && <p className="py-5 text-center text-sm text-slate-500">{t("Keine passenden Server verfügbar.", "No matching servers available.")}</p>}</div><p className="mt-4 text-xs leading-5 text-slate-500">{t("Du kannst die Zuweisung später entfernen. Danach ist dieser Platz 30 Tage gesperrt.", "You can remove the assignment later. That slot will then be on cooldown for 30 days.")}</p><button disabled={busy || !selected || availableSlots < 1} onClick={() => void assign()} className={cn(action, "mt-4 w-full bg-white text-black")}>{busy && <Loader2 className="h-4 w-4 animate-spin" />}{t("Premium zuweisen", "Assign Premium")}</button></Modal>}
    {release && <Modal title={t("Premium-Server entfernen?", "Remove Premium server?")} closeLabel={t("Schließen", "Close")} danger busy={busy} close={() => setRelease(null)}><AlertTriangle className="h-8 w-8 text-red-300" /><p className="mt-3 font-bold text-white">{slotName(release)}</p><p className="mt-3 text-sm leading-6 text-slate-300">{t("Diese Premium-Zuweisung endet sofort. Auch nicht mehr verfügbare Server lassen sich entfernen. Deine Einstellungen bleiben gespeichert.", "This Premium assignment ends immediately. You can also remove unavailable servers. Your settings remain saved.")}</p><div className="mt-4 rounded-xl border border-red-400/20 bg-red-400/5 p-4 text-sm font-bold text-red-200">{t("Dieser Platz ist danach 30 Tage gesperrt. Die Sperre kann nicht rückgängig gemacht werden.", "This slot will be on cooldown for 30 days. The cooldown cannot be undone.")}</div><div className="mt-5 grid grid-cols-2 gap-3"><button disabled={busy} onClick={() => setRelease(null)} className={cn(action, "border border-slate-700 text-slate-300")}>{t("Abbrechen", "Cancel")}</button><button disabled={busy} onClick={() => void releaseSlot()} className={cn(action, "bg-red-500 text-white")}>{busy && <Loader2 className="h-4 w-4 animate-spin" />}{t("Entfernen", "Remove")}</button></div></Modal>}
  </div>;
}
