"use client";
import { useEffect, useState } from "react";
import { Crown, Loader2, Lock, Power, Snowflake } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/api";
import { cn } from "@/lib/utils";
const fmt=(v?:number)=>v?new Date(v*1000).toLocaleString("de-DE"):"–";
export function ServerPremiumPanel({guildId}:{guildId:string}){
 const [state,setState]=useState<any>(null),[busy,setBusy]=useState(false);
 const load=()=>api.getServerPremium(guildId).then(setState).catch((e:any)=>toast.error(e?.message||"Premiumstatus konnte nicht geladen werden."));
 useEffect(()=>{ void load(); },[guildId]);
 const choose=async(action:"keep"|"disable")=>{setBusy(true);try{setState(await api.setServerPremiumExpiryAction(guildId,action));toast.success("Ablaufverhalten gespeichert.")}catch(e:any){toast.error(e?.message||"Speichern fehlgeschlagen.")}finally{setBusy(false)}};
 if(!state)return <div className="grid min-h-52 place-items-center"><Loader2 className="animate-spin text-amber-400"/></div>;
 return <div className={cn("space-y-5",busy&&"pointer-events-none opacity-70")}><section className="rounded-3xl border border-amber-400/20 bg-gradient-to-br from-amber-500/[0.1] to-[#101014] p-6"><div className="flex gap-3"><Crown className="text-amber-300"/><div><h2 className="text-xl font-black text-white">Server-Premium</h2><p className="text-sm text-slate-400">{state.guild_name}</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Box label="Status" value={state.active?"Premium aktiv":state.frozen?"Abgelaufen · eingefroren":"Kein Premium"}/><Box label="Ablauf" value={fmt(state.expires_at)}/><Box label="Premium-Platz" value={state.assigned?`Platz ${state.slot_no} von 3`:"Nicht zugewiesen"}/><Box label="Zugeordnetes Konto" value={state.account_user_id||"–"}/></div></section>{state.assigned&&<section className="rounded-2xl border border-slate-800 bg-[#131318] p-5"><h3 className="font-black text-white">Was passiert nach Ablauf?</h3><p className="mt-1 text-xs leading-5 text-slate-400">Die Auswahl löscht niemals gespeicherte Inhalte. Ohne aktives Premium können Premium-Einstellungen nicht mehr verändert werden.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><Choice active={state.expiry_action==="keep"} onClick={()=>choose("keep")} icon={Snowflake} title="Eingefroren weiterlaufen" text="Bereits eingerichtete Premiumfunktionen laufen unverändert weiter, bleiben aber bis zur Verlängerung gesperrt und können nicht angepasst werden."/><Choice active={state.expiry_action==="disable"} onClick={()=>choose("disable")} icon={Power} title="Premiumfunktionen deaktivieren" text="Premiumfunktionen stoppen beim Ablauf. Einstellungen und Daten bleiben für eine spätere Verlängerung gespeichert."/></div>{state.frozen&&<div className="mt-4 flex gap-2 rounded-xl border border-blue-500/20 bg-blue-500/[0.05] p-4 text-xs text-blue-200"><Lock className="h-4 w-4 shrink-0"/>Die Konfiguration ist eingefroren. Verlängere Premium, um sie wieder bearbeiten zu können.</div>}</section>}</div>
}
function Box({label,value}:{label:string,value:string}){return <div className="rounded-xl border border-white/5 bg-black/20 p-4"><p className="text-[10px] uppercase text-slate-500">{label}</p><p className="mt-1 font-black text-white">{value}</p></div>}
function Choice({active,onClick,icon:Icon,title,text}:{active:boolean,onClick:()=>void,icon:any,title:string,text:string}){return <button onClick={onClick} className={cn("rounded-xl border p-4 text-left",active?"border-amber-400/40 bg-amber-400/[0.08]":"border-slate-800 hover:border-slate-700")}><Icon className="h-5 w-5 text-amber-300"/><p className="mt-3 font-black text-white">{title}</p><p className="mt-1 text-xs leading-5 text-slate-400">{text}</p></button>}
