"use client";

import React, { useEffect, useMemo, useState } from "react";
import {
  Activity, AlertTriangle, Bot, CheckCircle2, ChevronDown, CircleDot,
  Cloud, Code2, Database, ExternalLink, FileSearch, Flag, Gauge,
  HardDrive, KeyRound, Loader2, LockKeyhole, RefreshCw, Search,
  Server, Settings, ShieldCheck, Siren, Terminal, Ticket, Users, Wrench, XCircle,
} from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/api";
import { ChannelPicker } from "@/components/dashboard/pickers";

const SUPPORT_GUILD_ID = "1530378233579704370";
const INPUT = "w-full rounded-xl border border-white/10 bg-[#15171d] px-4 py-3 text-sm text-white outline-none transition focus:border-blue-500/60";
const CARD = "rounded-2xl border border-white/[.07] bg-[#101116]";
type Tab = "overview"|"errors"|"diagnose"|"incidents"|"features"|"lookup"|"access";

function date(value: any) { return value ? new Date(Number(value) * 1000).toLocaleString("de-DE") : "–"; }
function Status({ok,label}:{ok:boolean;label:string}) { return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-bold ${ok?"bg-emerald-500/10 text-emerald-300":"bg-rose-500/10 text-rose-300"}`}>{ok?<CheckCircle2 className="h-3.5 w-3.5"/>:<XCircle className="h-3.5 w-3.5"/>}{label}</span> }
function Metric({icon:Icon,label,value}:{icon:any;label:string;value:any}) { return <div className={CARD+" p-5"}><div className="mb-4 grid h-10 w-10 place-items-center rounded-xl bg-blue-500/10 text-blue-300"><Icon className="h-5 w-5"/></div><p className="text-2xl font-black text-white">{value}</p><p className="mt-1 text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p></div> }
function Section({title,description,icon:Icon,children}:{title:string;description?:string;icon:any;children:React.ReactNode}) { return <section className={CARD+" overflow-hidden"}><header className="flex items-start gap-3 border-b border-white/[.06] p-5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-500/10 text-blue-300"><Icon className="h-5 w-5"/></span><div><h2 className="font-black text-white">{title}</h2>{description&&<p className="mt-1 text-sm text-slate-500">{description}</p>}</div></header><div className="p-5">{children}</div></section> }

export function SupportOperationsPanel({guildId}:{guildId:string}) {
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const [loadError,setLoadError]=useState<string|null>(null);
 const [tab,setTab]=useState<Tab>("overview"),[errorChannel,setErrorChannel]=useState("");
 const [targetGuild,setTargetGuild]=useState(""),[diagnosis,setDiagnosis]=useState<any>(null),[server,setServer]=useState<any>(null);
 const [incident,setIncident]=useState({title:"",severity:"medium",description:""});
 const [featureQuery,setFeatureQuery]=useState("");
 const [premiumIds,setPremiumIds]=useState({server:"",user:""}),[premium,setPremium]=useState<any>(null);
 const [accessIds,setAccessIds]=useState({server:"",user:""}),[accessCase,setAccessCase]=useState<any>(null);
 const [templateId,setTemplateId]=useState(""),[template,setTemplate]=useState<any>(null);
 const [confirm,setConfirm]=useState<{title:string;description:string;run:()=>Promise<any>}|null>(null);
 const load=async()=>{setLoading(true);setLoadError(null);try{const result=await api.getSupportOperations(guildId);setData(result);setErrorChannel(result.settings?.error_channel_id||"")}catch(error:any){setLoadError(error?.message||"Owner-Konsole konnte nicht geladen werden.")}finally{setLoading(false)}};
 useEffect(()=>{if(guildId===SUPPORT_GUILD_ID)load()},[guildId]); // eslint-disable-line
 const execute=async(action:()=>Promise<any>,success:string)=>{setBusy(true);try{await action();toast.success(success);setConfirm(null);await load();return true}catch(error:any){toast.error(error?.message||"Aktion fehlgeschlagen.");return false}finally{setBusy(false)}};
 const ask=(title:string,description:string,run:()=>Promise<any>)=>setConfirm({title,description,run});
 const features=useMemo(()=>((data?.features||[]) as any[]).filter(item=>`${item.label} ${item.key} ${item.category}`.toLowerCase().includes(featureQuery.toLowerCase())),[data,featureQuery]);
 if(guildId!==SUPPORT_GUILD_ID)return <div className="grid min-h-[420px] place-items-center text-slate-500"><LockKeyhole className="h-10 w-10"/></div>;
 if(loading&&!data)return <div className="grid min-h-[420px] place-items-center"><Loader2 className="h-7 w-7 animate-spin text-blue-400"/></div>;
 if(!data)return <div role="alert" className={CARD+" p-6 text-slate-300"}><p>{loadError||"Keine Daten verfügbar."}</p><button onClick={load} className="mt-4 rounded-xl bg-blue-600 px-5 py-3 text-white">Erneut versuchen</button></div>;
 const g=data?.global||{},deployment=data?.deployment||{};
 const tabs:[Tab,string,any][]=[["overview","Übersicht",Gauge],["errors","Fehlerzentrale",AlertTriangle],["diagnose","Diagnose",Wrench],["incidents","Incidents",Siren],["features","Feature Flags",Flag],["lookup","Server & Premium",Search],["access","Zugriffe & Templates",KeyRound]];
 return <div className="mx-auto max-w-7xl space-y-5 pb-24">
  <header className="rounded-3xl border border-blue-500/15 bg-gradient-to-br from-blue-500/[.08] to-transparent p-6 sm:p-8"><div className="flex flex-wrap items-start gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl border border-blue-400/20 bg-blue-500/10 text-blue-300"><ShieldCheck className="h-7 w-7"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-black text-white sm:text-3xl">Owner Operations</h1><span className="rounded-full border border-amber-400/20 bg-amber-400/10 px-3 py-1 text-xs font-black uppercase text-amber-300">Support Server exklusiv</span></div><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Globale Systemkontrolle, Fehlerberichte, Diagnosen, Incidents, Feature Flags und sichere Supportzugriffe. Nur feste OWNER_IDS erhalten Zugriff.</p></div><button onClick={load} disabled={loading} className="rounded-xl border border-white/10 bg-white/[.04] p-3 text-slate-300 hover:text-white"><RefreshCw className={`h-5 w-5 ${loading?"animate-spin":""}`}/></button></div></header>
  {loadError&&<div role="alert" className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-300">{loadError} Die angezeigten Daten stammen vom letzten erfolgreichen Abruf.</div>}
  <nav className="flex gap-2 overflow-x-auto rounded-2xl border border-white/[.07] bg-[#0d0e12] p-2">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`flex shrink-0 items-center gap-2 rounded-xl px-4 py-3 text-sm font-bold transition ${tab===id?"bg-blue-600 text-white":"text-slate-500 hover:bg-white/[.04] hover:text-slate-200"}`}><Icon className="h-4 w-4"/>{label}</button>)}</nav>

  {tab==="overview"&&<div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Metric icon={Server} label="Server" value={(g.guilds||0).toLocaleString("de-DE")}/><Metric icon={Users} label="Nutzer" value={(g.users||0).toLocaleString("de-DE")}/><Metric icon={Terminal} label="Commands" value={(g.commands||0).toLocaleString("de-DE")}/><Metric icon={Activity} label="Ping" value={`${g.latency_ms||0} ms`}/><Metric icon={AlertTriangle} label="Offene Fehler" value={g.open_errors||0}/><Metric icon={Siren} label="Incidents" value={g.open_incidents||0}/></div><div className="grid gap-5 lg:grid-cols-2"><Section title="Deployment" description="Livezustand der aktuellen Botinstanz" icon={Cloud}><div className="space-y-3 text-sm"><Row label="Deployment" value={deployment.deployment_id}/><Row label="Commit" value={deployment.commit}/><Row label="Instanz" value={deployment.instance}/><Row label="Discord" value={deployment.discord_status}/><Row label="Uptime" value={`${Math.floor((deployment.uptime_seconds||0)/3600)} Stunden`}/><Row label="Letztes Backup" value={date(deployment.last_backup_at)}/><div className="pt-2"><Status ok={!deployment.failed_extensions?.length} label={deployment.failed_extensions?.length?`${deployment.failed_extensions.length} Extensions fehlgeschlagen`:"Alle Extensions geladen"}/></div></div></Section><Section title="Private Fehlerzentrale" description="Automatische Berichte dürfen niemals öffentlich sichtbar sein" icon={Settings}><ChannelPicker guildId={guildId} value={errorChannel} onChange={value=>setErrorChannel(value||"")} placeholder="Privaten Fehlerkanal auswählen…"/><button disabled={busy||!errorChannel} onClick={()=>execute(()=>api.setSupportErrorChannel(guildId,errorChannel),"Fehlerkanal gespeichert.")} className="mt-4 rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-40">Einstellung speichern</button><p className="mt-3 text-xs text-slate-600">Der Bot prüft, dass @everyone den Kanal nicht sehen kann und dass Nachrichten, Verlauf und Threads erlaubt sind.</p></Section></div></div>}

  {tab==="errors"&&<Section title="Globale Fehlerzentrale" description="Gleiche Fehler werden anhand ihres Fingerprints zusammengeführt" icon={AlertTriangle}><div className="space-y-3">{(data?.errors||[]).map((error:any)=><details key={error.error_id} className="group rounded-xl border border-white/[.07] bg-[#15161b]"><summary className="flex cursor-pointer list-none items-center gap-3 p-4"><span className={`h-2.5 w-2.5 rounded-full ${error.status==="resolved"?"bg-emerald-400":error.status==="investigating"?"bg-amber-400":"bg-rose-400"}`}/><code className="text-xs font-bold text-blue-300">{error.error_id}</code><span className="min-w-0 flex-1 truncate text-sm font-bold text-white">{error.feature}</span><span className="text-xs text-slate-500">{error.count}×</span><ChevronDown className="h-4 w-4 text-slate-600 transition group-open:rotate-180"/></summary><div className="space-y-4 border-t border-white/[.06] p-4"><div className="grid gap-2 text-sm sm:grid-cols-2"><Row label="Typ" value={error.error_type}/><Row label="Instanz" value={error.bot_instance}/><Row label="Server-ID" value={error.guild_id||"System/DM"}/><Row label="Zuletzt" value={date(error.last_seen)}/></div><p className="rounded-lg bg-black/20 p-3 text-sm text-slate-300">{error.summary||"Keine Kurzmeldung"}</p><pre className="max-h-64 overflow-auto whitespace-pre-wrap rounded-lg border border-white/[.05] bg-black/30 p-3 text-[11px] leading-5 text-slate-400">{error.traceback}</pre><div className="flex flex-wrap gap-2"><button onClick={()=>execute(()=>api.setSupportErrorStatus(guildId,error.error_id,"investigating"),"Status aktualisiert.")} className="rounded-lg bg-amber-500/10 px-3 py-2 text-xs font-bold text-amber-300">Untersuchen</button><button onClick={()=>execute(()=>api.setSupportErrorStatus(guildId,error.error_id,"resolved"),"Fehler als behoben markiert.")} className="rounded-lg bg-emerald-500/10 px-3 py-2 text-xs font-bold text-emerald-300">Behoben</button><button onClick={()=>execute(()=>api.setSupportErrorStatus(guildId,error.error_id,"new"),"Fehler wieder geöffnet.")} className="rounded-lg bg-white/5 px-3 py-2 text-xs font-bold text-slate-300">Wieder öffnen</button><button onClick={()=>execute(()=>api.createSupportDeveloperTicket(guildId,error.error_id),"Entwickler-Ticket erstellt.")} className="rounded-lg bg-blue-500/10 px-3 py-2 text-xs font-bold text-blue-300"><Ticket className="mr-1 inline h-3.5 w-3.5"/>Entwickler-Ticket</button>{error.ticket_thread_id&&<span className="px-2 py-2 text-xs text-slate-500">Thread: {error.ticket_thread_id}</span>}</div></div></details>)}{!data?.errors?.length&&<Empty text="Noch keine Fehler erfasst."/>}</div></Section>}

  {tab==="diagnose"&&<Section title="Server-Diagnose" description="Nicht-destruktiver Health-Check mit konkreten Lösungsvorschlägen" icon={Wrench}><div className="flex flex-col gap-3 sm:flex-row"><input className={INPUT} value={targetGuild} onChange={e=>setTargetGuild(e.target.value.replace(/\D/g,""))} placeholder="Server-ID"/><button disabled={busy||!targetGuild} onClick={()=>execute(async()=>setDiagnosis(await api.diagnoseSupportServer(guildId,targetGuild)),"Diagnose abgeschlossen.")} className="shrink-0 rounded-xl bg-blue-600 px-5 py-3 font-bold text-white disabled:opacity-40">Diagnose starten</button></div>{diagnosis&&<div className="mt-6 space-y-3"><div className="flex items-center justify-between"><h3 className="font-black text-white">{diagnosis.guild?.name}</h3><span className="text-xs text-slate-500">{diagnosis.checked} Konfigurationen geprüft</span></div>{diagnosis.findings?.map((finding:any,index:number)=><div key={index} className={`rounded-xl border p-4 ${finding.severity==="ok"?"border-emerald-500/20 bg-emerald-500/[.05]":finding.severity==="high"||finding.severity==="critical"?"border-rose-500/20 bg-rose-500/[.05]":"border-amber-500/20 bg-amber-500/[.04]"}`}><div className="flex gap-3"><CircleDot className="mt-0.5 h-4 w-4 shrink-0 text-slate-400"/><div><b className="text-sm text-white">{finding.area}</b><p className="mt-1 text-sm text-slate-300">{finding.problem}</p><p className="mt-2 text-xs text-blue-300">Lösung: {finding.solution}</p></div></div></div>)}</div>}</Section>}

  {tab==="incidents"&&<div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><Section title="Incident eröffnen" description="Dokumentiert Störungen mit Schweregrad und Zeitlinie" icon={Siren}><div className="space-y-3"><input className={INPUT} value={incident.title} onChange={e=>setIncident({...incident,title:e.target.value})} placeholder="Titel"/><select className={INPUT} value={incident.severity} onChange={e=>setIncident({...incident,severity:e.target.value})}><option value="low">Niedrig</option><option value="medium">Mittel</option><option value="high">Hoch</option><option value="critical">Kritisch</option></select><textarea className={INPUT+" min-h-28"} value={incident.description} onChange={e=>setIncident({...incident,description:e.target.value})} placeholder="Beschreibung und aktuelle Auswirkungen"/><button disabled={busy||!incident.title.trim()} onClick={()=>execute(()=>api.createSupportIncident(guildId,incident),"Incident eröffnet.").then(ok=>{if(ok)setIncident({title:"",severity:"medium",description:""})})} className="w-full rounded-xl bg-blue-600 py-3 font-bold text-white disabled:opacity-40">Incident eröffnen</button></div></Section><Section title="Incident-Verlauf" icon={Activity}><div className="space-y-3">{(data?.incidents||[]).map((item:any)=><div key={item.incident_id} className="rounded-xl border border-white/[.07] bg-[#15161b] p-4"><div className="flex flex-wrap items-center gap-2"><code className="text-xs text-blue-300">{item.incident_id}</code><Status ok={item.status==="resolved"} label={item.status}/><span className="text-xs uppercase text-slate-500">{item.severity}</span></div><h3 className="mt-3 font-bold text-white">{item.title}</h3><p className="mt-1 text-sm text-slate-400">{item.description}</p><div className="mt-4 flex gap-2">{item.status!=="monitoring"&&item.status!=="resolved"&&<button onClick={()=>ask("Incident auf Beobachtung setzen?",`${item.incident_id}: ${item.title}`,()=>api.updateSupportIncident(guildId,item.incident_id,{status:"monitoring",note:"Über Dashboard auf Beobachtung gesetzt"}))} className="rounded-lg bg-amber-500/10 px-3 py-2 text-xs font-bold text-amber-300">Beobachten</button>}{item.status!=="resolved"&&<button onClick={()=>ask("Incident abschließen?","Der Incident bleibt in der Historie, wird aber als behoben markiert.",()=>api.updateSupportIncident(guildId,item.incident_id,{status:"resolved",note:"Über Dashboard abgeschlossen"}))} className="rounded-lg bg-emerald-500/10 px-3 py-2 text-xs font-bold text-emerald-300">Abschließen</button>}</div></div>)}</div></Section></div>}

  {tab==="features"&&<Section title="Feature Flags" description="Globale Änderungen benötigen immer eine Vorschau und Bestätigung" icon={Flag}><div className="relative mb-5"><Search className="absolute left-4 top-3.5 h-4 w-4 text-slate-600"/><input className={INPUT+" pl-11"} value={featureQuery} onChange={e=>setFeatureQuery(e.target.value)} placeholder="Feature Flag suchen…"/></div><div className="space-y-2">{features.map((feature:any)=><div key={feature.key} className="grid gap-3 rounded-xl border border-white/[.07] bg-[#15161b] p-4 lg:grid-cols-[1fr_auto_auto]"><div><div className="flex flex-wrap gap-2"><b className="text-sm text-white">{feature.label}</b><code className="text-[10px] text-slate-600">{feature.key}</code></div><p className="mt-1 text-xs text-slate-500">{feature.description}</p></div><label className="flex items-center gap-2 text-xs text-slate-400">Rollout<input type="number" min={0} max={100} key={`${feature.key}:${feature.rollout_percent}`} defaultValue={feature.rollout_percent} onBlur={e=>{const value=Math.max(0,Math.min(100,Number(e.target.value)));if(value!==feature.rollout_percent)ask("Rollout ändern?",`${feature.label}: ${feature.rollout_percent}% → ${value}%`,()=>api.updateSupportFeature(guildId,feature.key,{rollout:value}))}} className="w-20 rounded-lg border border-white/10 bg-black/20 p-2 text-white"/>%</label><button onClick={()=>ask(`${feature.enabled?"Deaktivieren":"Aktivieren"}?`,`${feature.label}\n${feature.effect}`,()=>api.updateSupportFeature(guildId,feature.key,{enabled:!feature.enabled}))} className={`rounded-xl px-4 py-2 text-xs font-black ${feature.enabled?"bg-emerald-500/10 text-emerald-300":"bg-slate-800 text-slate-400"}`}>{feature.enabled?"Aktiv":"Aus"}</button></div>)}</div></Section>}

  {tab==="lookup"&&<div className="space-y-5"><div className="grid gap-5 lg:grid-cols-2"><Section title="Server-Lookup" description="Geheime globale Serveransicht" icon={Server}><div className="flex gap-2"><input className={INPUT} value={targetGuild} onChange={e=>setTargetGuild(e.target.value.replace(/\D/g,""))} placeholder="Server-ID"/><button disabled={busy||!targetGuild} onClick={()=>execute(async()=>setServer(await api.lookupSupportServer(guildId,targetGuild)),"Server geladen.")} className="rounded-xl bg-blue-600 px-4 text-white"><Search/></button></div>{server&&<div className="mt-5 space-y-2 text-sm"><h3 className="text-lg font-black text-white">{server.name}</h3><Row label="Server-ID" value={server.id}/><Row label="Owner" value={`${server.owner_name} (${server.owner_id})`}/><Row label="Mitglieder" value={server.members}/><Row label="Kanäle / Rollen" value={`${server.channels} / ${server.roles}`}/><Row label="Premium" value={server.premium?.active?"Aktiv":"Nein"}/><div className="pt-2"><Status ok={server.bot_permissions?.send_messages} label="Nachrichten"/> <Status ok={server.bot_permissions?.manage_roles} label="Rollen"/></div></div>}</Section><Section title="Premium-Historie" description="Account-, Serverplatz- und Kaufhistorie ohne Änderungen" icon={Database}><div className="space-y-3"><input className={INPUT} value={premiumIds.server} onChange={e=>setPremiumIds({...premiumIds,server:e.target.value.replace(/\D/g,"")})} placeholder="Server-ID (optional)"/><input className={INPUT} value={premiumIds.user} onChange={e=>setPremiumIds({...premiumIds,user:e.target.value.replace(/\D/g,"")})} placeholder="Nutzer-ID (optional)"/><button disabled={busy||(!premiumIds.server&&!premiumIds.user)} onClick={()=>execute(async()=>setPremium(await api.getSupportPremiumHistory(guildId,premiumIds.server,premiumIds.user)),"Premium-Historie geladen.")} className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white disabled:opacity-40">Historie laden</button></div>{premium&&<pre className="mt-5 max-h-96 overflow-auto whitespace-pre-wrap rounded-xl bg-black/20 p-4 text-xs text-slate-400">{JSON.stringify(premium,null,2)}</pre>}</Section></div></div>}

  {tab==="access"&&<div className="grid gap-5 lg:grid-cols-2"><Section title="Supportzugriff" description="Zugriff prüfen oder nach Bestätigung sofort widerrufen" icon={LockKeyhole}><div className="space-y-3"><input className={INPUT} value={accessIds.server} onChange={e=>setAccessIds({...accessIds,server:e.target.value.replace(/\D/g,"")})} placeholder="Server-ID"/><input className={INPUT} value={accessIds.user} onChange={e=>setAccessIds({...accessIds,user:e.target.value.replace(/\D/g,"")})} placeholder="Supporter-ID"/><button disabled={busy||!accessIds.server||!accessIds.user} onClick={()=>execute(async()=>setAccessCase((await api.getSupportAccessCase(guildId,accessIds.server,accessIds.user)).case || {status:"none",problem:"Kein Supportfall gefunden."}),"Supportfall geprüft.")} className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white disabled:opacity-40">Zugriff prüfen</button></div>{accessCase&&<div className="mt-5 space-y-2 rounded-xl border border-white/[.07] bg-black/20 p-4 text-sm"><Row label="Fall" value={`#${accessCase.id}`}/><Row label="Status" value={accessCase.status}/><Row label="Problem" value={accessCase.problem||"–"}/><Row label="Akzeptiert" value={date(accessCase.accepted_at)}/>{["pending","accepted"].includes(accessCase.status)&&<button onClick={()=>ask("Supportzugriff widerrufen?","Der Fall wird geschlossen und der Dashboardzugriff endet sofort. Der Audit-Verlauf bleibt bestehen.",async()=>{await api.revokeSupportAccessCase(guildId,accessIds.server,accessIds.user);setAccessCase((current:any)=>current?{...current,status:"closed"}:current)})} className="mt-3 rounded-xl bg-rose-600 px-4 py-2 font-bold text-white">Zugriff widerrufen</button>}</div>}</Section><Section title="Template-Inspektor" description="Sichere Metadaten- und Secret-Prüfung ohne Payload-Ausgabe" icon={FileSearch}><div className="flex gap-2"><input className={INPUT} value={templateId} onChange={e=>setTemplateId(e.target.value.replace(/\D/g,""))} placeholder="Template-ID"/><button disabled={busy||!templateId} onClick={()=>execute(async()=>setTemplate(await api.inspectSupportTemplate(guildId,Number(templateId))),"Vorlage geprüft.")} className="rounded-xl bg-blue-600 px-4 text-white"><FileSearch/></button></div>{template&&<div className="mt-5 space-y-2 text-sm"><h3 className="font-black text-white">{template.template?.name}</h3><Row label="Sichtbarkeit" value={template.template?.visibility}/><Row label="Quelle" value={template.template?.source_guild_id}/><Row label="Größe" value={`${template.inspection?.size||0} Zeichen`}/><Row label="Bereiche" value={template.inspection?.modules?.join(", ")||"keine"}/><Status ok={!template.inspection?.contains_secret} label={template.inspection?.contains_secret?"Möglicher geheimer Wert":"Secret-Prüfung unauffällig"}/></div>}</Section></div>}

  {confirm&&<div className="fixed inset-0 z-[120] grid place-items-center bg-black/75 p-4"><div className="w-full max-w-lg rounded-3xl border border-rose-500/20 bg-[#15161b] p-6 shadow-2xl"><div className="flex items-center gap-3"><AlertTriangle className="h-6 w-6 text-rose-400"/><h2 className="text-xl font-black text-white">{confirm.title}</h2></div><p className="mt-4 whitespace-pre-line text-sm leading-6 text-slate-400">{confirm.description}</p><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setConfirm(null)} className="px-4 py-3 text-sm font-bold text-slate-400">Abbrechen</button><button disabled={busy} onClick={()=>execute(confirm.run,"Änderung gespeichert.")} className="rounded-xl bg-rose-600 px-5 py-3 text-sm font-black text-white disabled:opacity-50">{busy?"Wird ausgeführt …":"Endgültig bestätigen"}</button></div></div></div>}
 </div>
}
function Row({label,value}:{label:string;value:any}){return <div className="flex items-start justify-between gap-4 border-b border-white/[.05] py-2 last:border-0"><span className="text-slate-500">{label}</span><span className="max-w-[65%] break-words text-right font-medium text-slate-200">{String(value??"–")}</span></div>}
function Empty({text}:{text:string}){return <div className="grid min-h-40 place-items-center rounded-xl border border-dashed border-white/10 text-sm text-slate-600">{text}</div>}
