const assert=require('node:assert/strict');const {test}=require('node:test');const fs=require('node:fs');const path=require('node:path');const Module=require('node:module');const ts=require('typescript');const {NextRequest}=require('next/server');
const root=path.resolve(__dirname,'..'),resolve=Module._resolveFilename,compile=Module._extensions['.ts'],load=Module._load,fetch=global.fetch;
let session={user:{id:'870179991462236170'}},allowed=true,calls=[];
Module._resolveFilename=function(name,...args){return resolve.call(this,name.startsWith('@/')?path.join(root,name.slice(2)):name,...args)};
Module._load=function(name,...args){if(name==='next-auth/next')return {getServerSession:async()=>session};if(name==='@/lib/auth')return {authOptions:{}};if(name==='@/lib/guild-auth')return {verifyGuildAccess:async()=>({allowed,status:403,reason:'Denied'}),fetchBanState:async()=>({banned:false}),isGlobalAdmin:()=>false,isOwnerId:()=>false,hasTeamPermission:async()=>false};return load.call(this,name,...args)};
Module._extensions['.ts']=(mod,file)=>mod._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);
const route=require('../app/api/bot/[...path]/route.ts');
global.fetch=async(url,options)=>{calls.push({url:String(url),options});return new Response('{}',{headers:{'content-type':'application/json'}})};
test.after(()=>{global.fetch=fetch;Module._resolveFilename=resolve;Module._load=load;if(compile)Module._extensions['.ts']=compile;else delete Module._extensions['.ts']});
async function request(suffix,method='GET',body){const parts=['tickets','1530378233579704370','ai',...suffix];return route[method](new NextRequest('http://localhost/api/bot/'+parts.join('/'),{method,body:body&&JSON.stringify(body)}),{params:{path:parts}})}
test('coaching requires a signed-in account admitted to the guild',async()=>{session=null;assert.equal((await request(['chat'])).status,401);session={user:{id:'870179991462236170'}};allowed=false;assert.equal((await request(['chat'],'POST',{message:'fact'})).status,403);assert.equal(calls.length,0);allowed=true});
test('personal coaching identity always comes from the session',async()=>{calls=[];assert.equal((await request(['chat'],'POST',{actor:'forged',message:'Premium costs 5 euros',mode:'teach'})).status,200);const body=JSON.parse(calls[0].options.body);assert.equal(body.actor,session.user.id);assert.equal(new URL(calls[0].url).searchParams.get('actor'),session.user.id);assert.equal(body.message,'Premium costs 5 euros')});
test('history deletion and memory edits retain the server and actor boundary',async()=>{calls=[];await request(['chat'],'DELETE');await request(['memories'],'PUT',{id:12,title:'Premium',content:'6 euros',actor:'forged'});assert.ok(calls.every(c=>c.url.includes('/tickets/1530378233579704370/ai/')));assert.ok(calls.every(c=>new URL(c.url).searchParams.get('actor')===session.user.id));assert.equal(JSON.parse(calls[1].options.body).actor,session.user.id)});
